In [3]:
import pandas as pd
from datalab_beta import *

In [16]:
#graph_data=pd.read_csv('World Cup 2018 Dataset.csv')
#graph_data

In [5]:
world_people=pd.read_csv('world people lifestyle.csv')
#world_people
world_people['Country'] = world_people.Country.apply(text_norm)

In [11]:
#
#world_people
world_people = world_people.rename(columns={'Country': 'country'})
#df_player.sort_values('country')
#df_player=pd.read_csv('spi_player.csv')
#df_player.sort_values('country')
world_people['country']=world_people['country'].replace(['united kingdom'], 'england')
world_people['country']=world_people['country'].replace(['colombia'], 'columbia')
#world_people = world_people.append({'country' : 'south korea' , 'Happiness.Rank' : 0} , ignore_index=True)
#world_people['country']=world_people['country'].replace(['united kingdom'], 'england')
world_people=world_people[['country','Happiness.Score','Health..Life.Expectancy.','Freedom','Generosity','Trust..Government.Corruption.']]
world_people

,country,Happiness.Score,Health..Life.Expectancy.,Freedom,Generosity,Trust..Government.Corruption.
0,norway,7.537,0.796667,0.635423,0.362012,0.315964
1,denmark,7.522,0.792566,0.626007,0.355280,0.400770
2,iceland,7.504,0.833552,0.627163,0.475540,0.153527
3,switzerland,7.494,0.858131,0.620071,0.290549,0.367007
4,finland,7.469,0.809158,0.617951,0.245483,0.382612
5,netherlands,7.377,0.810696,0.585384,0.470490,0.282662
6,canada,7.316,0.834558,0.611101,0.435540,0.287372
7,new zealand,7.314,0.816760,0.614062,0.500005,0.382817
8,sweden,7.284,0.830875,0.612924,0.385399,0.384399
9,australia,7.284,0.843887,0.601607,0.477699,0.301184
10,israel,7.213,0.838404,0.405989,0.330083,0.085242
11,costa rica,7.079,0.759509,0.580132,0.214613,0.100107
12,austria,7.006,0.815328,0.567766,0.316472,0.221060
13,united states,6.993,0.774287,0.505741,0.392579,0.135639
14,ireland,6.977,0.809783,0.573110,0.427858,0.298388
15,germany,6.951,0.798951,0.562511,0.336269,0.276732
16,belgium,6.891,0.818092,0.539771,0.231503,0.251343
17,luxembourg,6.863,0.845089,0.596628,0.283181,0.318834
18,england,6.714,0.805336,0.508190,0.492774,0.265428
19,chile,6.652,0.819480,0.376895,0.326662,0.082288
20,united arab emirates,6.648,0.726798,0.608345,0.360942,0.324490
21,brazil,6.635,0.616552,0.437454,0.162350,0.111093
22,czech republic,6.609,0.754444,0.490946,0.088107,0.036873
23,argentina,6.599,0.695137,0.494519,0.109457,0.059740
24,mexico,6.578,0.709979,0.412730,0.120990,0.132774
25,singapore,6.572,0.949492,0.549841,0.345966,0.464308
26,malta,6.527,0.821944,0.588767,0.574731,0.153066
27,uruguay,6.454,0.719217,0.579392,0.175097,0.178062
28,guatemala,6.454,0.540240,0.531311,0.283488,0.077223
29,panama,6.452,0.706156,0.550027,0.210557,0.070984
...,...,...,...,...,...,...
125,congo (kinshasa),4.280,0.191407,0.235961,0.246456,0.060241
126,mali,4.190,0.169366,0.306614,0.183354,0.104970
127,ivory coast,4.180,0.048642,0.447706,0.201237,0.130062
128,cambodia,4.168,0.429783,0.633376,0.385923,0.068106
129,sudan,4.139,0.290921,0.014996,0.182317,0.089848
130,ghana,4.120,0.295638,0.423026,0.256924,0.025336
131,ukraine,4.096,0.575904,0.122975,0.270061,0.023029
132,uganda,4.081,0.217633,0.443186,0.325766,0.057070
133,burkina faso,4.032,0.215844,0.324368,0.250865,0.120328
134,niger,4.028,0.268505,0.363659,0.228674,0.138573
135,malawi,3.970,0.315090,0.466915,0.287170,0.072712
136,chad,3.936,0.041135,0.162342,0.216114,0.053582
137,zimbabwe,3.875,0.196764,0.336384,0.189143,0.095375
138,lesotho,3.808,0.000000,0.390661,0.157497,0.119095
139,angola,3.795,0.049869,0.000000,0.097926,0.069720
140,afghanistan,3.794,0.180747,0.106180,0.311871,0.061158
141,botswana,3.766,0.341756,0.505196,0.099348,0.098583
142,benin,3.657,0.209930,0.425963,0.207948,0.060929
143,madagascar,3.644,0.375223,0.189197,0.208733,0.067232
144,haiti,3.603,0.277321,0.030370,0.489204,0.099872
145,yemen,3.593,0.310081,0.249464,0.104125,0.056767
146,south sudan,3.591,0.163486,0.147062,0.285671,0.116794
147,liberia,3.533,0.229918,0.332881,0.266550,0.038948
148,guinea,3.507,0.194129,0.348588,0.264815,0.110938
149,togo,3.495,0.247106,0.380426,0.196896,0.095665
150,rwanda,3.471,0.326425,0.581844,0.252756,0.455220
151,syria,3.462,0.500533,0.081539,0.493664,0.151347
152,tanzania,3.349,0.364509,0.390018,0.354256,0.066035
153,burundi,2.905,0.151611,0.059901,0.204435,0.084148
154,central african republic,2.693,0.018773,0.270842,0.280876,0.056565

In [12]:
df_player=pd.read_csv('spi_player.csv')

In [13]:
df_player=df_player.drop('Unnamed: 0', 1)

In [18]:
df_p = pd.merge(df_player, world_people, how='inner', on='country')
df_p.to_csv('spi_player_happiness_final.csv')

In [17]:
df_p.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 32 entries, 0 to 31
Data columns (total 28 columns):
country                          32 non-null object
fifa_rank                        32 non-null int64
gdp_rank                         32 non-null int64
population_rank                  32 non-null int64
avg_age                          32 non-null float64
elo_ranking                      32 non-null int64
star_count                       32 non-null int64
coach_performance                32 non-null int64
home_country_adv                 32 non-null int64
home_continent_adv               32 non-null int64
% of player in foreign club      32 non-null float64
Previous_final                   32 non-null int64
Previous_semi_final              32 non-null int64
last_best_performance            32 non-null int64
att                              32 non-null int64
mid                              32 non-null int64
def                              32 non-null int64
ovr                              32 non-null int64
spi                              32 non-null float64
global_o                         32 non-null float64
global_d                         32 non-null float64
avg_players_appearance           32 non-null float64
avg_players_goal                 32 non-null float64
Happiness.Score                  32 non-null float64
Health..Life.Expectancy.         32 non-null float64
Freedom                          32 non-null float64
Generosity                       32 non-null float64
Trust..Government.Corruption.    32 non-null float64
dtypes: float64(12), int64(15), object(1)
memory usage: 7.2+ KB

In [106]:
world_cup_stats=pd.read_csv('wc_forecasts.csv')
#world_cup_stats.iloc[224:256]

,forecast_timestamp,team,group,spi,global_o,global_d,sim_wins,sim_ties,sim_losses,sim_goal_diff,...,group_1,group_2,group_3,group_4,make_round_of_16,make_quarters,make_semis,make_final,win_league,timestamp
224,2018-06-13 15:00:46 UTC,Brazil,E,92.81522,3.10876,0.30493,2.02480,0.63266,0.34254,4.04483,...,0.67564,0.21840,0.08291,0.02305,0.89404,0.65871,0.46291,0.30835,0.19259,2018-07-15 16:55:47 UTC
225,2018-06-13 15:00:46 UTC,Spain,B,91.30254,3.21114,0.46145,1.90567,0.67013,0.42420,3.52194,...,0.60657,0.26126,0.09883,0.03334,0.86783,0.70556,0.47535,0.28990,0.17486,2018-07-15 16:55:47 UTC
226,2018-06-13 15:00:46 UTC,Germany,F,90.61094,3.23346,0.52224,2.05956,0.57317,0.36727,4.36945,...,0.68292,0.21230,0.08279,0.02199,0.89522,0.58603,0.39949,0.23557,0.13305,2018-07-15 16:55:47 UTC
227,2018-06-13 15:00:46 UTC,France,C,87.17682,2.88582,0.56975,1.90986,0.63823,0.45191,3.65002,...,0.61025,0.24509,0.10739,0.03727,0.85534,0.53285,0.31150,0.15725,0.07884,2018-07-15 16:55:47 UTC
228,2018-06-13 15:00:46 UTC,Argentina,D,87.41192,2.58581,0.39899,1.60352,0.82229,0.57419,2.22487,...,0.47970,0.28915,0.15456,0.07659,0.76885,0.49485,0.26548,0.13841,0.07004,2018-07-15 16:55:47 UTC
229,2018-06-13 15:00:46 UTC,Belgium,G,85.40682,2.81096,0.63262,1.86493,0.62705,0.50802,3.48920,...,0.49955,0.37140,0.10064,0.02841,0.87095,0.58640,0.27298,0.14032,0.06613,2018-07-15 16:55:47 UTC
230,2018-06-13 15:00:46 UTC,England,G,83.72824,2.34392,0.45752,1.76783,0.71267,0.51950,2.85787,...,0.43839,0.41026,0.11734,0.03401,0.84865,0.57501,0.27141,0.13954,0.06535,2018-07-15 16:55:47 UTC
231,2018-06-13 15:00:46 UTC,Portugal,B,83.46619,2.40348,0.50431,1.36327,0.83786,0.79887,1.12869,...,0.27963,0.40523,0.21860,0.09654,0.68486,0.46394,0.25357,0.12211,0.05532,2018-07-15 16:55:47 UTC
232,2018-06-13 15:00:46 UTC,Croatia,D,80.38099,2.28947,0.58512,1.31289,0.85741,0.82970,1.04557,...,0.31877,0.32370,0.22183,0.13570,0.64247,0.34850,0.16137,0.07114,0.03005,2018-07-15 16:55:47 UTC
233,2018-06-13 15:00:46 UTC,Colombia,H,80.52894,2.18240,0.51246,1.42086,0.87723,0.70191,1.48243,...,0.40540,0.28219,0.19253,0.11988,0.68759,0.32028,0.12797,0.05394,0.02128,2018-07-15 16:55:47 UTC
234,2018-06-13 15:00:46 UTC,Uruguay,A,79.52363,2.28530,0.62285,1.60644,0.76680,0.62676,2.26712,...,0.44315,0.31742,0.16886,0.07057,0.76057,0.29347,0.13021,0.05050,0.01852,2018-07-15 16:55:47 UTC
235,2018-06-13 15:00:46 UTC,Switzerland,E,78.14181,2.28471,0.68735,1.11761,0.79458,1.08781,0.04250,...,0.17229,0.35799,0.29639,0.17333,0.53028,0.22852,0.11048,0.04586,0.01733,2018-07-15 16:55:47 UTC
236,2018-06-13 15:00:46 UTC,Russia,A,70.14205,1.94268,0.80439,1.52605,0.79297,0.68098,1.89790,...,0.39334,0.33939,0.18757,0.07970,0.73273,0.25805,0.10662,0.03683,0.01253,2018-07-15 16:55:47 UTC
237,2018-06-13 15:00:46 UTC,Denmark,C,74.74844,2.13883,0.74455,1.18423,0.78091,1.03486,0.32555,...,0.21013,0.34497,0.27920,0.16570,0.55510,0.23159,0.08830,0.03160,0.01088,2018-07-15 16:55:47 UTC
238,2018-06-13 15:00:46 UTC,Sweden,F,73.86757,2.05513,0.72496,1.07606,0.78367,1.14027,-0.24287,...,0.15296,0.34307,0.31844,0.18553,0.49603,0.16519,0.07125,0.02691,0.00872,2018-07-15 16:55:47 UTC
239,2018-06-13 15:00:46 UTC,Serbia,E,73.82320,2.08408,0.74737,0.92961,0.78799,1.28240,-0.85485,...,0.11973,0.28976,0.34526,0.24525,0.40949,0.15346,0.06667,0.02452,0.00810,2018-07-15 16:55:47 UTC
240,2018-06-13 15:00:46 UTC,Poland,H,73.28044,2.18065,0.84065,1.15518,0.84352,1.00130,0.33550,...,0.27521,0.27299,0.24589,0.20591,0.54820,0.20791,0.06716,0.02300,0.00746,2018-07-15 16:55:47 UTC
241,2018-06-13 15:00:46 UTC,Mexico,F,75.77906,2.16425,0.71564,1.02236,0.77355,1.20409,-0.50567,...,0.13518,0.32323,0.33644,0.20515,0.45841,0.14623,0.06187,0.02276,0.00734,2018-07-15 16:55:47 UTC
242,2018-06-13 15:00:46 UTC,Morocco,B,72.33079,1.86875,0.65756,0.70100,0.83836,1.46064,-1.73852,...,0.07683,0.20432,0.37611,0.34274,0.28115,0.13647,0.04977,0.01558,0.00479,2018-07-15 16:55:47 UTC
243,2018-06-13 15:00:46 UTC,Peru,C,72.15616,1.97974,0.74528,0.94483,0.79077,1.26440,-0.74781,...,0.13536,0.27335,0.33959,0.25170,0.40871,0.14219,0.04569,0.01374,0.00387,2018-07-15 16:55:47 UTC
244,2018-06-13 15:00:46 UTC,Japan,H,71.43255,2.06588,0.84009,0.93493,0.85473,1.21034,-0.58988,...,0.18965,0.24082,0.27372,0.29581,0.43047,0.13797,0.03641,0.01110,0.00293,2018-07-15 16:55:47 UTC
245,2018-06-13 15:00:46 UTC,Nigeria,D,70.08336,1.81501,0.71082,0.71178,0.85814,1.43008,-1.49089,...,0.10189,0.19750,0.31877,0.38184,0.29939,0.10912,0.03490,0.01006,0.00288,2018-07-15 16:55:47 UTC
246,2018-06-13 15:00:46 UTC,Iceland,D,67.07394,1.92122,0.92018,0.70305,0.79968,1.49727,-1.77955,...,0.09964,0.18965,0.30484,0.40587,0.28929,0.10036,0.03139,0.00825,0.00211,2018-07-15 16:55:47 UTC
247,2018-06-13 15:00:46 UTC,Senegal,H,65.96802,1.65995,0.75761,0.75428,0.89402,1.35170,-1.22805,...,0.12974,0.20400,0.28786,0.37840,0.33374,0.09086,0.02072,0.00561,0.00136,2018-07-15 16:55:47 UTC
248,2018-06-13 15:00:46 UTC,Iran,B,65.56769,1.60243,0.72717,0.46424,0.78529,1.75047,-2.91211,...,0.03697,0.12919,0.30646,0.52738,0.16616,0.06585,0.01902,0.00480,0.00113,2018-07-15 16:55:47 UTC
249,2018-06-13 15:00:46 UTC,Egypt,A,62.46236,1.60808,0.85654,0.84678,0.84175,1.31147,-0.97761,...,0.11932,0.22689,0.37570,0.27809,0.34621,0.06168,0.01617,0.00359,0.00092,2018-07-15 16:55:47 UTC
250,2018-06-13 15:00:46 UTC,Costa Rica,E,64.89752,1.73368,0.86128,0.47035,0.70003,1.82962,-3.23248,...,0.03234,0.13385,0.27544,0.55837,0.16619,0.03813,0.01227,0.00325,0.00064,2018-07-15 16:55:47 UTC
251,2018-06-13 15:00:46 UTC,Tunisia,G,59.59496,1.62315,0.98848,0.55839,0.69617,1.74544,-2.93305,...,0.03821,0.12307,0.41233,0.42639,0.16128,0.04906,0.00806,0.00154,0.00031,2018-07-15 16:55:47 UTC
252,2018-06-13 15:00:46 UTC,Australia,C,61.68548,1.79230,1.04721,0.51950,0.67325,1.80725,-3.22776,...,0.04426,0.13659,0.27382,0.54533,0.18085,0.04054,0.00865,0.00160,0.00028,2018-07-15 16:55:47 UTC
253,2018-06-13 15:00:46 UTC,South Korea,F,60.13670,1.61593,0.95934,0.44471,0.66423,1.89106,-3.62091,...,0.02894,0.12140,0.26233,0.58733,0.15034,0.02373,0.00564,0.00115,0.00022,2018-07-15 16:55:47 UTC
254,2018-06-13 15:00:46 UTC,Panama,G,56.47272,1.45612,0.96652,0.45386,0.67409,1.87205,-3.41402,...,0.02385,0.09527,0.36969,0.51119,0.11912,0.03251,0.00471,0.00091,0.00011,2018-07-15 16:55:47 UTC
255,2018-06-13 15:00:46 UTC,Saudi Arabia,A,51.33380,1.47177,1.20177,0.46546,0.70902,1.82552,-3.18741,...,0.04419,0.11630,0.26787,0.57164,0.16049,0.01498,0.00201,0.00031,0.00006,2018-07-15 16:55:47 UTC

In [113]:
spi_data=world_cup_stats[['team','spi','global_o','global_d']]
spi_data=spi_data.iloc[224:256]
spi_data['team'] = spi_data.team.apply(text_norm)
spi_data = spi_data.rename(columns={'team': 'country'})
spi_data['country']=spi_data['country'].replace(['colombia'], 'columbia')

In [114]:
spi_data

          country       spi  global_o  global_d
224        brazil  92.81522   3.10876   0.30493
225         spain  91.30254   3.21114   0.46145
226       germany  90.61094   3.23346   0.52224
227        france  87.17682   2.88582   0.56975
228     argentina  87.41192   2.58581   0.39899
229       belgium  85.40682   2.81096   0.63262
230       england  83.72824   2.34392   0.45752
231      portugal  83.46619   2.40348   0.50431
232       croatia  80.38099   2.28947   0.58512
233      columbia  80.52894   2.18240   0.51246
234       uruguay  79.52363   2.28530   0.62285
235   switzerland  78.14181   2.28471   0.68735
236        russia  70.14205   1.94268   0.80439
237       denmark  74.74844   2.13883   0.74455
238        sweden  73.86757   2.05513   0.72496
239        serbia  73.82320   2.08408   0.74737
240        poland  73.28044   2.18065   0.84065
241        mexico  75.77906   2.16425   0.71564
242       morocco  72.33079   1.86875   0.65756
243          peru  72.15616   1.97974   0.74528
244         japan  71.43255   2.06588   0.84009
245       nigeria  70.08336   1.81501   0.71082
246       iceland  67.07394   1.92122   0.92018
247       senegal  65.96802   1.65995   0.75761
248          iran  65.56769   1.60243   0.72717
249         egypt  62.46236   1.60808   0.85654
250    costa rica  64.89752   1.73368   0.86128
251       tunisia  59.59496   1.62315   0.98848
252     australia  61.68548   1.79230   1.04721
253   south korea  60.13670   1.61593   0.95934
254        panama  56.47272   1.45612   0.96652
255  saudi arabia  51.33380   1.47177   1.20177

In [122]:
integrate_features=pd.read_csv('FinalDataSet/integratefeatures.csv')
integrate_features=integrate_features.drop('Unnamed: 0', 1)
#integrate_features
df = pd.merge(integrate_features, spi_data, how='inner', on='country')
df.to_csv('integratespi.csv')
df

,country,fifa_rank,gdp_rank,population_rank,avg_age,elo_ranking,star_count,coach_performance,home_country_adv,home_continent_adv,...,Previous_final,Previous_semi_final,last_best_performance,att,mid,def,ovr,spi,global_o,global_d
0,russia,70,60,9,28.1,1697,1,32,1,1,...,0,1,14,79,77,75,79,70.14205,1.94268,0.80439
1,saudi arabia,67,37,47,28.7,1574,0,9,0,0,...,0,0,33,71,72,71,72,51.33380,1.47177,1.20177
2,egypt,45,132,14,27.0,1659,1,15,0,0,...,0,0,51,75,77,74,76,62.46236,1.60808,0.85654
3,uruguay,14,45,133,28.7,1866,3,7,0,0,...,2,5,10,86,77,80,80,79.52363,2.28530,0.62285
4,portugal,4,36,84,27.7,1995,3,5,0,0,...,0,2,24,88,83,82,84,83.46619,2.40348,0.50431
5,spain,10,31,28,28.0,2031,6,4,0,1,...,1,2,6,84,86,85,85,91.30254,3.21114,0.46145
6,morocco,41,125,40,27.2,1691,0,8,0,0,...,0,0,39,74,77,77,76,72.33079,1.86875,0.65756
7,iran,37,92,17,26.5,1799,0,14,0,0,...,0,0,36,74,73,73,74,65.56769,1.60243,0.72717
8,france,7,24,21,26.4,1989,5,12,0,1,...,2,5,7,86,84,82,85,87.17682,2.88582,0.56975
9,australia,36,10,56,26.9,1727,0,23,0,0,...,0,0,32,69,72,70,72,61.68548,1.79230,1.04721
10,peru,11,84,43,27.0,1881,0,11,0,0,...,0,0,38,78,75,74,76,72.15616,1.97974,0.74528
11,denmark,12,9,116,26.1,1842,1,19,0,1,...,0,0,40,76,79,76,78,74.74844,2.13883,0.74455
12,argentina,5,53,31,28.4,1984,4,3,0,0,...,5,5,4,86,82,81,84,87.41192,2.58581,0.39899
13,iceland,22,4,178,29.0,1811,0,10,0,1,...,0,0,77,75,78,74,75,67.07394,1.92122,0.92018
14,croatia,20,56,128,27.5,1856,3,30,0,0,...,0,1,34,81,82,78,80,80.38099,2.28947,0.58512
15,nigeria,48,139,7,24.9,1696,0,20,0,0,...,0,0,30,75,76,72,75,70.08336,1.81501,0.71082
16,brazil,2,66,5,27.8,2114,4,2,0,0,...,7,11,1,87,85,84,86,92.81522,3.10876,0.30493
17,switzerland,6,2,98,26.6,1866,0,13,0,1,...,0,0,13,76,77,78,78,78.14181,2.28471,0.68735
18,costa rica,23,58,123,29.0,1746,1,28,0,0,...,0,0,37,69,73,73,73,64.89752,1.73368,0.86128
19,serbia,34,89,102,27.7,1769,0,31,0,1,...,0,2,11,76,81,78,78,73.82320,2.08408,0.74737
20,germany,1,17,19,25.7,2109,6,1,0,1,...,8,13,2,85,85,85,86,90.61094,3.23346,0.52224
21,mexico,15,70,11,27.4,1848,0,16,0,0,...,0,0,5,81,79,77,79,75.77906,2.16425,0.71564
22,sweden,24,11,91,27.4,1825,1,24,0,1,...,1,4,12,78,76,77,77,73.86757,2.05513,0.72496
23,south korea,57,28,27,26.5,1760,1,25,0,0,...,0,1,15,71,74,70,73,60.13670,1.61593,0.95934
24,belgium,3,18,77,27.0,1927,5,21,0,1,...,0,1,9,85,83,83,83,85.40682,2.81096,0.63262
25,panama,55,51,131,29.4,1671,0,17,0,0,...,0,0,77,68,69,69,69,56.47272,1.45612,0.96652
26,tunisia,21,118,79,26.8,1624,0,26,0,0,...,0,0,35,73,72,72,73,59.59496,1.62315,0.98848
27,england,21,22,22,25.9,1933,2,22,0,1,...,1,2,8,83,81,80,81,83.72824,2.34392,0.45752
28,poland,8,55,36,28.0,1842,2,18,0,1,...,0,2,22,83,78,78,80,73.28044,2.18065,0.84065
29,senegal,27,155,71,26.4,1752,1,29,0,0,...,0,0,54,77,77,76,76,65.96802,1.65995,0.75761
30,columbia,16,85,29,27.3,1927,3,6,0,0,...,0,0,31,82,78,78,79,80.52894,2.18240,0.51246
31,japan,61,25,10,27.5,1706,0,27,0,0,...,0,0,29,76,78,73,75,71.43255,2.06588,0.84009

In [123]:
player=pd.read_csv('world_cup_2018_player.csv')

In [138]:
player=player[['country','caps','goals']]
#groupby_sum1 = groupby_sum1.rename(columns={'country': 'country1'})
player['country']=player.country.apply(text_norm)
player['country']=player['country'].replace(['uraguay'], 'uruguay')

In [139]:
groupby_sum1=player
groupby_sum1 = groupby_sum1.groupby(['country']).mean() 
#groupby_sum1 = groupby_sum1.rename(columns={'country': 'country1'})
groupby_sum1 = groupby_sum1.rename(columns={'caps': 'avg_players_appearance'})
groupby_sum1 = groupby_sum1.rename(columns={'goals': 'avg_players_goal'})
#groupby_sum1['country']=groupby_sum1.country.apply(text_norm)
#groupby_sum1

In [140]:
groupby_sum1

              avg_players_appearance  avg_players_goal
country
argentina                  37.347826          7.478261
australia                  29.826087          5.260870
belgium                    47.260870          6.782609
brazil                     29.869565          5.521739
columbia                   31.000000          3.956522
costa rica                 51.347826          5.000000
croatia                    40.304348          5.043478
denmark                    26.565217          2.826087
egypt                      37.304348          2.782609
england                    20.956522          2.565217
france                     26.043478          3.782609
germany                    41.086957          6.913043
iceland                    40.043478          3.521739
iran                       30.521739          4.739130
japan                      45.000000          7.086957
mexico                     60.304348          9.000000
morocco                    24.043478          2.608696
nigeria                    25.608696          2.434783
panama                     58.478261          6.304348
peru                       34.086957          4.130435
poland                     35.478261          5.478261
portugal                   39.521739          6.173913
russia                     28.521739          2.434783
saudi arabia               34.304348          3.956522
senegal                    27.130435          3.173913
serbia                     25.956522          2.826087
south korea                29.304348          3.347826
spain                      42.217391          4.565217
sweden                     31.304348          3.173913
switzerland                37.347826          4.260870
tunisia                    20.173913          1.565217
uruguay                    42.260870          5.826087

In [141]:
#groupby_sum1['country']=groupby_sum1['country'].replace(['uraguay'], 'uruguay')

In [142]:
df_player = pd.merge(df, groupby_sum1, how='inner', on='country')

In [152]:
#df_player.to_csv('spi_player.csv')
df_player

,country,fifa_rank,gdp_rank,population_rank,avg_age,elo_ranking,star_count,coach_performance,home_country_adv,home_continent_adv,...,last_best_performance,att,mid,def,ovr,spi,global_o,global_d,avg_players_appearance,avg_players_goal
0,russia,70,60,9,28.1,1697,1,32,1,1,...,14,79,77,75,79,70.14205,1.94268,0.80439,28.521739,2.434783
1,saudi arabia,67,37,47,28.7,1574,0,9,0,0,...,33,71,72,71,72,51.33380,1.47177,1.20177,34.304348,3.956522
2,egypt,45,132,14,27.0,1659,1,15,0,0,...,51,75,77,74,76,62.46236,1.60808,0.85654,37.304348,2.782609
3,uruguay,14,45,133,28.7,1866,3,7,0,0,...,10,86,77,80,80,79.52363,2.28530,0.62285,42.260870,5.826087
4,portugal,4,36,84,27.7,1995,3,5,0,0,...,24,88,83,82,84,83.46619,2.40348,0.50431,39.521739,6.173913
5,spain,10,31,28,28.0,2031,6,4,0,1,...,6,84,86,85,85,91.30254,3.21114,0.46145,42.217391,4.565217
6,morocco,41,125,40,27.2,1691,0,8,0,0,...,39,74,77,77,76,72.33079,1.86875,0.65756,24.043478,2.608696
7,iran,37,92,17,26.5,1799,0,14,0,0,...,36,74,73,73,74,65.56769,1.60243,0.72717,30.521739,4.739130
8,france,7,24,21,26.4,1989,5,12,0,1,...,7,86,84,82,85,87.17682,2.88582,0.56975,26.043478,3.782609
9,australia,36,10,56,26.9,1727,0,23,0,0,...,32,69,72,70,72,61.68548,1.79230,1.04721,29.826087,5.260870
10,peru,11,84,43,27.0,1881,0,11,0,0,...,38,78,75,74,76,72.15616,1.97974,0.74528,34.086957,4.130435
11,denmark,12,9,116,26.1,1842,1,19,0,1,...,40,76,79,76,78,74.74844,2.13883,0.74455,26.565217,2.826087
12,argentina,5,53,31,28.4,1984,4,3,0,0,...,4,86,82,81,84,87.41192,2.58581,0.39899,37.347826,7.478261
13,iceland,22,4,178,29.0,1811,0,10,0,1,...,77,75,78,74,75,67.07394,1.92122,0.92018,40.043478,3.521739
14,croatia,20,56,128,27.5,1856,3,30,0,0,...,34,81,82,78,80,80.38099,2.28947,0.58512,40.304348,5.043478
15,nigeria,48,139,7,24.9,1696,0,20,0,0,...,30,75,76,72,75,70.08336,1.81501,0.71082,25.608696,2.434783
16,brazil,2,66,5,27.8,2114,4,2,0,0,...,1,87,85,84,86,92.81522,3.10876,0.30493,29.869565,5.521739
17,switzerland,6,2,98,26.6,1866,0,13,0,1,...,13,76,77,78,78,78.14181,2.28471,0.68735,37.347826,4.260870
18,costa rica,23,58,123,29.0,1746,1,28,0,0,...,37,69,73,73,73,64.89752,1.73368,0.86128,51.347826,5.000000
19,serbia,34,89,102,27.7,1769,0,31,0,1,...,11,76,81,78,78,73.82320,2.08408,0.74737,25.956522,2.826087
20,germany,1,17,19,25.7,2109,6,1,0,1,...,2,85,85,85,86,90.61094,3.23346,0.52224,41.086957,6.913043
21,mexico,15,70,11,27.4,1848,0,16,0,0,...,5,81,79,77,79,75.77906,2.16425,0.71564,60.304348,9.000000
22,sweden,24,11,91,27.4,1825,1,24,0,1,...,12,78,76,77,77,73.86757,2.05513,0.72496,31.304348,3.173913
23,south korea,57,28,27,26.5,1760,1,25,0,0,...,15,71,74,70,73,60.13670,1.61593,0.95934,29.304348,3.347826
24,belgium,3,18,77,27.0,1927,5,21,0,1,...,9,85,83,83,83,85.40682,2.81096,0.63262,47.260870,6.782609
25,panama,55,51,131,29.4,1671,0,17,0,0,...,77,68,69,69,69,56.47272,1.45612,0.96652,58.478261,6.304348
26,tunisia,21,118,79,26.8,1624,0,26,0,0,...,35,73,72,72,73,59.59496,1.62315,0.98848,20.173913,1.565217
27,england,21,22,22,25.9,1933,2,22,0,1,...,8,83,81,80,81,83.72824,2.34392,0.45752,20.956522,2.565217
28,poland,8,55,36,28.0,1842,2,18,0,1,...,22,83,78,78,80,73.28044,2.18065,0.84065,35.478261,5.478261
29,senegal,27,155,71,26.4,1752,1,29,0,0,...,54,77,77,76,76,65.96802,1.65995,0.75761,27.130435,3.173913
30,columbia,16,85,29,27.3,1927,3,6,0,0,...,31,82,78,78,79,80.52894,2.18240,0.51246,31.000000,3.956522
31,japan,61,25,10,27.5,1706,0,27,0,0,...,29,76,78,73,75,71.43255,2.06588,0.84009,45.000000,7.086957

In [103]:
#player_stats.nunique()
#player_stats.info()

#df_player = df_player.reindex(sorted(df_player.columns), axis=1)
#df_player.sort_values('country')

,country,fifa_rank,gdp_rank,population_rank,avg_age,elo_ranking,star_count,coach_performance,home_country_adv,home_continent_adv,...,last_best_performance,att,mid,def,ovr,spi,global_o,global_d,avg_players_appearance,avg_players_goal
11,argentina,5,53,31,28.4,1984,4,3,0,0,...,4,86,82,81,84,87.41192,2.58581,0.39899,37.347826,7.478261
8,australia,36,10,56,26.9,1727,0,23,0,0,...,32,69,72,70,72,61.68548,1.79230,1.04721,29.826087,5.260870
23,belgium,3,18,77,27.0,1927,5,21,0,1,...,9,85,83,83,83,85.40682,2.81096,0.63262,47.260870,6.782609
15,brazil,2,66,5,27.8,2114,4,2,0,0,...,1,87,85,84,86,92.81522,3.10876,0.30493,29.869565,5.521739
17,costa rica,23,58,123,29.0,1746,1,28,0,0,...,37,69,73,73,73,64.89752,1.73368,0.86128,51.347826,5.000000
13,croatia,20,56,128,27.5,1856,3,30,0,0,...,34,81,82,78,80,80.38099,2.28947,0.58512,40.304348,5.043478
10,denmark,12,9,116,26.1,1842,1,19,0,1,...,40,76,79,76,78,74.74844,2.13883,0.74455,26.565217,2.826087
2,egypt,45,132,14,27.0,1659,1,15,0,0,...,51,75,77,74,76,62.46236,1.60808,0.85654,37.304348,2.782609
26,england,21,22,22,25.9,1933,2,22,0,1,...,8,83,81,80,81,83.72824,2.34392,0.45752,20.956522,2.565217
7,france,7,24,21,26.4,1989,5,12,0,1,...,7,86,84,82,85,87.17682,2.88582,0.56975,26.043478,3.782609
19,germany,1,17,19,25.7,2109,6,1,0,1,...,2,85,85,85,86,90.61094,3.23346,0.52224,41.086957,6.913043
12,iceland,22,4,178,29.0,1811,0,10,0,1,...,77,75,78,74,75,67.07394,1.92122,0.92018,40.043478,3.521739
6,iran,37,92,17,26.5,1799,0,14,0,0,...,36,74,73,73,74,65.56769,1.60243,0.72717,30.521739,4.739130
29,japan,61,25,10,27.5,1706,0,27,0,0,...,29,76,78,73,75,71.43255,2.06588,0.84009,45.000000,7.086957
20,mexico,15,70,11,27.4,1848,0,16,0,0,...,5,81,79,77,79,75.77906,2.16425,0.71564,60.304348,9.000000
5,morocco,41,125,40,27.2,1691,0,8,0,0,...,39,74,77,77,76,72.33079,1.86875,0.65756,24.043478,2.608696
14,nigeria,48,139,7,24.9,1696,0,20,0,0,...,30,75,76,72,75,70.08336,1.81501,0.71082,25.608696,2.434783
24,panama,55,51,131,29.4,1671,0,17,0,0,...,77,68,69,69,69,56.47272,1.45612,0.96652,58.478261,6.304348
9,peru,11,84,43,27.0,1881,0,11,0,0,...,38,78,75,74,76,72.15616,1.97974,0.74528,34.086957,4.130435
27,poland,8,55,36,28.0,1842,2,18,0,1,...,22,83,78,78,80,73.28044,2.18065,0.84065,35.478261,5.478261
3,portugal,4,36,84,27.7,1995,3,5,0,0,...,24,88,83,82,84,83.46619,2.40348,0.50431,39.521739,6.173913
0,russia,70,60,9,28.1,1697,1,32,1,1,...,14,79,77,75,79,70.14205,1.94268,0.80439,28.521739,2.434783
1,saudi arabia,67,37,47,28.7,1574,0,9,0,0,...,33,71,72,71,72,51.33380,1.47177,1.20177,34.304348,3.956522
28,senegal,27,155,71,26.4,1752,1,29,0,0,...,54,77,77,76,76,65.96802,1.65995,0.75761,27.130435,3.173913
18,serbia,34,89,102,27.7,1769,0,31,0,1,...,11,76,81,78,78,73.82320,2.08408,0.74737,25.956522,2.826087
22,south korea,57,28,27,26.5,1760,1,25,0,0,...,15,71,74,70,73,60.13670,1.61593,0.95934,29.304348,3.347826
4,spain,10,31,28,28.0,2031,6,4,0,1,...,6,84,86,85,85,91.30254,3.21114,0.46145,42.217391,4.565217
21,sweden,24,11,91,27.4,1825,1,24,0,1,...,12,78,76,77,77,73.86757,2.05513,0.72496,31.304348,3.173913
16,switzerland,6,2,98,26.6,1866,0,13,0,1,...,13,76,77,78,78,78.14181,2.28471,0.68735,37.347826,4.260870
25,tunisia,21,118,79,26.8,1624,0,26,0,0,...,35,73,72,72,73,59.59496,1.62315,0.98848,20.173913,1.565217

In [54]:
df_player = pd.merge(player, player_score, how='inner', on='player')

In [4]:
group_result=pd.read_csv('groupresultfinal.csv')

FileNotFoundError: [Errno 2] File b'groupresultfinal.csv' does not exist: b'groupresultfinal.csv'

In [1]:
group_result

NameError: name 'group_result' is not defined

In [33]:
fifa_index=pd.read_csv('fifaindex.csv')

In [34]:
fifa_index.head()

   Unnamed: 0   country  att  mid  def  ovr
0           0    brazil   87   85   84   86
1           1   germany   85   85   85   86
2           2    france   86   84   82   85
3           3     spain   84   86   85   85
4           4  portugal   88   83   82   84

In [35]:
initial_feature=pd.read_csv('Featuresdata.csv',';')

In [36]:
initial_feature.head()

,id,country,group,fifa_rank,gdp_rank,population_rank,avg_age,elo_ranking,star_count,coach_performance,home_country_adv,home_continent_adv,% of player in foreign club,Previous_final,Previous_semi_final,last_best_performance
0,1,Russia,A,70,60,9,28.1,1697,NaN,NaN,1,1,0.05,0,1,NaN
1,2,Saudi Arabia,A,67,37,47,28.7,1574,NaN,NaN,0,0,0.00,0,0,NaN
2,3,Egypt,A,45,132,14,27.0,1659,NaN,NaN,0,0,0.58,0,0,NaN
3,4,Uruguay,A,14,45,133,28.7,1866,NaN,NaN,0,0,0.88,2,5,NaN
4,5,Portugal,B,4,36,84,27.7,1995,NaN,NaN,0,0,0.71,0,2,NaN

In [37]:
final_feature=pd.read_csv('finalfeaturetable.csv')

In [38]:
final_feature.head()

,Unnamed: 0,country,fifa_rank,gdp_rank,population_rank,avg_age,elo_ranking,home_country_adv,home_continent_adv,% of player in foreign club,Previous_final,Previous_semi_final,att,mid,def,ovr
0,0,russia,70,60,9,28.1,1697,1,1,0.05,0,1,79,77,75,79
1,1,saudi arabia,67,37,47,28.7,1574,0,0,0.00,0,0,71,72,71,72
2,2,egypt,45,132,14,27.0,1659,0,0,0.58,0,0,75,77,74,76
3,3,uruguay,14,45,133,28.7,1866,0,0,0.88,2,5,86,77,80,80
4,4,portugal,4,36,84,27.7,1995,0,0,0.71,0,2,88,83,82,84

In [39]:
final_csv=pd.read_csv('integrateddata.csv')

In [40]:
final_csv.head()

,Unnamed: 0,home,away,home_score,away_score,neutral,fifa_rank1,elo1,continent1,final1,...,fifa_rank,elo,continent,final,semi,club,att,def,mid,ovr
0,0,russia,saudi arabia,5,0,1,70.0,1697.0,1.0,0.0,...,3.0,123.0,1.0,0.0,0.0,0.05,8.0,4.0,5.0,7.0
1,1,egypt,uruguay,0,1,0,45.0,1659.0,0.0,0.0,...,31.0,-207.0,0.0,-2.0,0.0,-0.30,-11.0,-6.0,0.0,-4.0
2,2,morocco,iran,0,1,0,41.0,1691.0,0.0,0.0,...,4.0,-108.0,0.0,0.0,0.0,0.43,0.0,4.0,4.0,2.0
3,3,portugal,spain,3,3,0,4.0,1995.0,0.0,0.0,...,-6.0,-36.0,-1.0,-1.0,0.0,0.36,4.0,-3.0,-3.0,-1.0
4,4,france,australia,2,1,0,7.0,1989.0,1.0,2.0,...,-29.0,262.0,1.0,2.0,0.0,-0.14,17.0,12.0,12.0,13.0

In [ ]:
#fifaindex=pd.read_csv('fifaindex.csv')
#fifaindex = fifaindex.drop('Unnamed: 0', 1)
#fifaindex.to_csv('FinalDataSet/fifaindex.csv') export the final fifa index
#features=pd.read_csv('AllFeaturesdata.csv',';')
#features.head()
#features['country'] = features.country.apply(text_norm)
#features['country']=features['country'].replace(['costrica'], 'costa rica')
#features = features.drop('id', 1)
#features.to_csv('FinalDataSet/features.csv')
#group_result=pd.read_csv('groupresultfinal.csv')
#group_result.head()
#group_result=group_result.drop('Unnamed: 0', 1)
#group_result=group_result.drop('neutral', 1)
#group_result = group_result.rename(columns={'home': 'team_1'})
#group_result = group_result.rename(columns={'away': 'team_2'})
#group_result = group_result.rename(columns={'home_score': 'team_1_score'})
#group_result = group_result.rename(columns={'away_score': 'team_2_score'})
#group=group_result
#group.head()
#cols = list(group)
#cols[1], cols[0] = cols[0], cols[1]
#cols[3], cols[2] = cols[2], cols[3]

#cols
#group=group.ix[:,cols]
#group = group.rename(columns={'team_11': 'team_1'})
#group = group.rename(columns={'team_22': 'team_2'})
#group = group.rename(columns={'team_11_score': 'team_1_score'})
#group = group.rename(columns={'team_22_score': 'team_2_score'})
#group_result_final=group_result.append(group)
#group_result_final.to_csv('FinalDataSet/group_result_final.csv')