In [195]:
import pandas as pd
from datalab_beta import *
import warnings
warnings.filterwarnings('ignore')

In [196]:
team_wise_features=pd.read_csv('Team_wise_all_features.csv')
team_wise_features=team_wise_features.drop('Unnamed: 0', 1)

In [197]:
#team_wise_features
df=team_wise_features

In [198]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32 entries, 0 to 31
Data columns (total 28 columns):
country                          32 non-null object
fifa_rank                        32 non-null int64
gdp_rank                         32 non-null int64
population_rank                  32 non-null int64
avg_age                          32 non-null float64
elo_ranking                      32 non-null int64
star_count                       32 non-null int64
coach_performance                32 non-null int64
home_country_adv                 32 non-null int64
home_continent_adv               32 non-null int64
% of player in foreign club      32 non-null float64
Previous_final                   32 non-null int64
Previous_semi_final              32 non-null int64
last_best_performance            32 non-null int64
att                              32 non-null int64
mid                              32 non-null int64
def                              32 non-null int64
ovr                              32 non-null int64
spi                              32 non-null float64
global_o                         32 non-null float64
global_d                         32 non-null float64
avg_players_appearance           32 non-null float64
avg_players_goal                 32 non-null float64
Happiness.Score                  32 non-null float64
Health..Life.Expectancy.         32 non-null float64
Freedom                          32 non-null float64
Generosity                       32 non-null float64
Trust..Government.Corruption.    32 non-null float64
dtypes: float64(12), int64(15), object(1)
memory usage: 7.1+ KB

In [199]:
integrate_features_happy=pd.read_csv('spi_player_happiness.csv')
integrate_features_happy=integrate_features_happy.drop('Unnamed: 0', 1)

In [200]:
integrate_features_happy

,country,fifa_rank,gdp_rank,population_rank,avg_age,elo_ranking,star_count,coach_performance,home_country_adv,home_continent_adv,...,att,mid,def,ovr,spi,global_o,global_d,avg_players_appearance,avg_players_goal,Happiness.Rank
0,russia,70,60,9,28.1,1697,1,32,1,1,...,79,77,75,79,70.14205,1.94268,0.80439,28.521739,2.434783,49
1,saudi arabia,67,37,47,28.7,1574,0,9,0,0,...,71,72,71,72,51.33380,1.47177,1.20177,34.304348,3.956522,37
2,egypt,45,132,14,27.0,1659,1,15,0,0,...,75,77,74,76,62.46236,1.60808,0.85654,37.304348,2.782609,104
3,uruguay,14,45,133,28.7,1866,3,7,0,0,...,86,77,80,80,79.52363,2.28530,0.62285,42.260870,5.826087,28
4,portugal,4,36,84,27.7,1995,3,5,0,0,...,88,83,82,84,83.46619,2.40348,0.50431,39.521739,6.173913,89
5,spain,10,31,28,28.0,2031,6,4,0,1,...,84,86,85,85,91.30254,3.21114,0.46145,42.217391,4.565217,34
6,morocco,41,125,40,27.2,1691,0,8,0,0,...,74,77,77,76,72.33079,1.86875,0.65756,24.043478,2.608696,84
7,iran,37,92,17,26.5,1799,0,14,0,0,...,74,73,73,74,65.56769,1.60243,0.72717,30.521739,4.739130,108
8,france,7,24,21,26.4,1989,5,12,0,1,...,86,84,82,85,87.17682,2.88582,0.56975,26.043478,3.782609,31
9,australia,36,10,56,26.9,1727,0,23,0,0,...,69,72,70,72,61.68548,1.79230,1.04721,29.826087,5.260870,10
10,peru,11,84,43,27.0,1881,0,11,0,0,...,78,75,74,76,72.15616,1.97974,0.74528,34.086957,4.130435,63
11,denmark,12,9,116,26.1,1842,1,19,0,1,...,76,79,76,78,74.74844,2.13883,0.74455,26.565217,2.826087,2
12,argentina,5,53,31,28.4,1984,4,3,0,0,...,86,82,81,84,87.41192,2.58581,0.39899,37.347826,7.478261,24
13,iceland,22,4,178,29.0,1811,0,10,0,1,...,75,78,74,75,67.07394,1.92122,0.92018,40.043478,3.521739,3
14,croatia,20,56,128,27.5,1856,3,30,0,0,...,81,82,78,80,80.38099,2.28947,0.58512,40.304348,5.043478,77
15,nigeria,48,139,7,24.9,1696,0,20,0,0,...,75,76,72,75,70.08336,1.81501,0.71082,25.608696,2.434783,95
16,brazil,2,66,5,27.8,2114,4,2,0,0,...,87,85,84,86,92.81522,3.10876,0.30493,29.869565,5.521739,22
17,switzerland,6,2,98,26.6,1866,0,13,0,1,...,76,77,78,78,78.14181,2.28471,0.68735,37.347826,4.260870,4
18,costa rica,23,58,123,29.0,1746,1,28,0,0,...,69,73,73,73,64.89752,1.73368,0.86128,51.347826,5.000000,12
19,serbia,34,89,102,27.7,1769,0,31,0,1,...,76,81,78,78,73.82320,2.08408,0.74737,25.956522,2.826087,73
20,germany,1,17,19,25.7,2109,6,1,0,1,...,85,85,85,86,90.61094,3.23346,0.52224,41.086957,6.913043,16
21,mexico,15,70,11,27.4,1848,0,16,0,0,...,81,79,77,79,75.77906,2.16425,0.71564,60.304348,9.000000,25
22,sweden,24,11,91,27.4,1825,1,24,0,1,...,78,76,77,77,73.86757,2.05513,0.72496,31.304348,3.173913,9
23,south korea,57,28,27,26.5,1760,1,25,0,0,...,71,74,70,73,60.13670,1.61593,0.95934,29.304348,3.347826,55
24,belgium,3,18,77,27.0,1927,5,21,0,1,...,85,83,83,83,85.40682,2.81096,0.63262,47.260870,6.782609,17
25,panama,55,51,131,29.4,1671,0,17,0,0,...,68,69,69,69,56.47272,1.45612,0.96652,58.478261,6.304348,30
26,tunisia,21,118,79,26.8,1624,0,26,0,0,...,73,72,72,73,59.59496,1.62315,0.98848,20.173913,1.565217,102
27,england,21,22,22,25.9,1933,2,22,0,1,...,83,81,80,81,83.72824,2.34392,0.45752,20.956522,2.565217,19
28,poland,8,55,36,28.0,1842,2,18,0,1,...,83,78,78,80,73.28044,2.18065,0.84065,35.478261,5.478261,46
29,senegal,27,155,71,26.4,1752,1,29,0,0,...,77,77,76,76,65.96802,1.65995,0.75761,27.130435,3.173913,115
30,columbia,16,85,29,27.3,1927,3,6,0,0,...,82,78,78,79,80.52894,2.18240,0.51246,31.000000,3.956522,36
31,japan,61,25,10,27.5,1706,0,27,0,0,...,76,78,73,75,71.43255,2.06588,0.84009,45.000000,7.086957,51

In [201]:
team_wise_result=pd.read_csv('final_result_all_matches.csv')
team_wise_result=team_wise_result.drop('Unnamed: 0', 1)

In [202]:
team_wise_result

         team_1        team_2  team_1_score  team_2_score
0        russia  saudi arabia             5             0
1         egypt       uruguay             0             1
2       morocco          iran             0             1
3      portugal         spain             3             3
4        france     australia             2             1
5     argentina       iceland             1             1
6          peru       denmark             0             1
7       croatia       nigeria             2             0
8    costa rica        serbia             0             1
9       germany        mexico             0             1
10       brazil   switzerland             1             1
11       sweden   south korea             1             0
12      belgium        panama             3             0
13      tunisia       england             1             2
14     columbia         japan             1             2
15       poland       senegal             1             2
16       russia         egypt             3             1
17     portugal       morocco             1             0
18      uruguay  saudi arabia             1             0
19         iran         spain             0             1
20      denmark     australia             1             1
21       france          peru             1             0
22    argentina       croatia             0             3
23       brazil    costa rica             2             0
24      nigeria       iceland             2             0
25       serbia   switzerland             1             2
26      belgium       tunisia             5             2
27  south korea        mexico             1             2
28      germany        sweden             2             1
29      england        panama             6             1
..          ...           ...           ...           ...
34         iran      portugal             1             1
35        spain       morocco             2             2
36      denmark        france             0             0
37    australia          peru             0             2
38      nigeria     argentina             1             2
39      iceland       croatia             1             2
40       mexico        sweden             0             3
41  south korea       germany             2             0
42       serbia        brazil             0             2
43  switzerland    costa rica             2             2
44        japan        poland             0             1
45      senegal      columbia             0             1
46       panama       tunisia             1             2
47      england       belgium             0             1
48       france     argentina             4             3
49      uruguay      portugal             2             1
50        spain        russia             1             1
51      croatia       denmark             1             1
52       brazil        mexico             2             0
53      belgium         japan             3             2
54       sweden   switzerland             1             0
55     columbia       england             1             1
56      uruguay        france             0             2
57       brazil       belgium             1             2
58       sweden       england             0             2
59       russia       croatia             2             2
60       france       belgium             1             0
61      england       croatia             1             2
62      belgium       england             2             0
63       france       croatia             4             2

[64 rows x 4 columns]

# Adding group stage

In [100]:
team_wise_result['stage']=0

In [101]:
#team_wise_result
team_wise_result.loc[48:55,'stage'] = 1

team_wise_result.loc[56:59,'stage'] = 2
team_wise_result.loc[60:61,'stage'] = 3
team_wise_result.loc[62,'stage'] = 4
team_wise_result.loc[63,'stage'] = 5

In [104]:
#team_wise_result
train_data_match_stage = team_wise_result.head(48)
train_data_match_stage.to_csv('train_data_match_stage.csv')
test_data_match_stage=team_wise_result.tail(16)
test_data_match_stage.to_csv('test_data_match_stage.csv')

In [106]:
test_data_match_stage

      team_1       team_2  team_1_score  team_2_score  stage
48    france    argentina             4             3      1
49   uruguay     portugal             2             1      1
50     spain       russia             1             1      1
51   croatia      denmark             1             1      1
52    brazil       mexico             2             0      1
53   belgium        japan             3             2      1
54    sweden  switzerland             1             0      1
55  columbia      england             1             1      1
56   uruguay       france             0             2      2
57    brazil      belgium             1             2      2
58    sweden      england             0             2      2
59    russia      croatia             2             2      2
60    france      belgium             1             0      3
61   england      croatia             1             2      3
62   belgium      england             2             0      4
63    france      croatia             4             2      5

In [119]:
train_data_match_stage

          team_1        team_2  team_1_score  team_2_score  stage
0         russia  saudi arabia             5             0      0
1          egypt       uruguay             0             1      0
2        morocco          iran             0             1      0
3       portugal         spain             3             3      0
4         france     australia             2             1      0
5      argentina       iceland             1             1      0
6           peru       denmark             0             1      0
7        croatia       nigeria             2             0      0
8     costa rica        serbia             0             1      0
9        germany        mexico             0             1      0
10        brazil   switzerland             1             1      0
11        sweden   south korea             1             0      0
12       belgium        panama             3             0      0
13       tunisia       england             1             2      0
14      columbia         japan             1             2      0
15        poland       senegal             1             2      0
16        russia         egypt             3             1      0
17      portugal       morocco             1             0      0
18       uruguay  saudi arabia             1             0      0
19          iran         spain             0             1      0
20       denmark     australia             1             1      0
21        france          peru             1             0      0
22     argentina       croatia             0             3      0
23        brazil    costa rica             2             0      0
24       nigeria       iceland             2             0      0
25        serbia   switzerland             1             2      0
26       belgium       tunisia             5             2      0
27   south korea        mexico             1             2      0
28       germany        sweden             2             1      0
29       england        panama             6             1      0
30         japan       senegal             2             2      0
31        poland      columbia             0             3      0
32       uruguay        russia             3             0      0
33  saudi arabia         egypt             2             1      0
34          iran      portugal             1             1      0
35         spain       morocco             2             2      0
36       denmark        france             0             0      0
37     australia          peru             0             2      0
38       nigeria     argentina             1             2      0
39       iceland       croatia             1             2      0
40        mexico        sweden             0             3      0
41   south korea       germany             2             0      0
42        serbia        brazil             0             2      0
43   switzerland    costa rica             2             2      0
44         japan        poland             0             1      0
45       senegal      columbia             0             1      0
46        panama       tunisia             1             2      0
47       england       belgium             0             1      0

In [98]:
test_data_match_stage

      team_1       team_2  team_1_score  team_2_score
48    france    argentina             4             3
49   uruguay     portugal             2             1
50     spain       russia             1             1
51   croatia      denmark             1             1
52    brazil       mexico             2             0
53   belgium        japan             3             2
54    sweden  switzerland             1             0
55  columbia      england             1             1
56   uruguay       france             0             2
57    brazil      belgium             1             2
58    sweden      england             0             2
59    russia      croatia             2             2
60    france      belgium             1             0
61   england      croatia             1             2
62   belgium      england             2             0
63    france      croatia             4             2

In [14]:
#group_result=group_result.drop('neutral', 1)
#group_result = group_result.rename(columns={'home': 'team_1'})
#group_result = group_result.rename(columns={'away': 'team_2'})
#group_result = group_result.rename(columns={'home_score': 'team_1_score'})
#group_result = group_result.rename(columns={'away_score': 'team_2_score'})
#group_result.to_csv('final_result_all_matches.csv')

In [231]:
group_result=pd.read_csv('all_data_test_train_29_16_15.csv')
group_result=group_result.drop('Unnamed: 0', 1)
#train_data_match_result = group_result.head(48)
#train_data_match_result.to_csv('train_data_match_result.csv')
##test_data_match_result=group_result.tail(16)
#test_data_match_result.to_csv('test_data_match_result.csv')

In [232]:
group_result

          team_1        team_2  team_1_score  team_2_score  stage
0         russia  saudi arabia             5             0      0
1          egypt       uruguay             0             1      0
2        morocco          iran             0             1      0
3       portugal         spain             3             3      0
4         france     australia             2             1      0
5      argentina       iceland             1             1      0
6           peru       denmark             0             1      0
7        croatia       nigeria             2             0      0
8     costa rica        serbia             0             1      0
9        germany        mexico             0             1      0
10        brazil   switzerland             1             1      0
11        sweden   south korea             1             0      0
12       belgium        panama             3             0      0
13       tunisia       england             1             2      0
14      columbia         japan             1             2      0
15        poland       senegal             1             2      0
16        russia         egypt             3             1      0
17      portugal       morocco             1             0      0
18       uruguay  saudi arabia             1             0      0
19          iran         spain             0             1      0
20       denmark     australia             1             1      0
21        france          peru             1             0      0
22     argentina       croatia             0             3      0
23        brazil    costa rica             2             0      0
24       nigeria       iceland             2             0      0
25        serbia   switzerland             1             2      0
26       belgium       tunisia             5             2      0
27   south korea        mexico             1             2      0
28       germany        sweden             2             1      0
29       england        panama             6             1      0
..           ...           ...           ...           ...    ...
98      portugal          iran             1             1      0
99       morocco         spain             2             2      0
100       france       denmark             0             0      0
101         peru     australia             2             0      0
102    argentina       nigeria             2             1      0
103      croatia       iceland             2             1      0
104       sweden        mexico             3             0      0
105      germany   south korea             0             2      0
106       brazil        serbia             2             0      0
107   costa rica   switzerland             2             2      0
108       poland         japan             1             0      0
109     columbia       senegal             1             0      0
110      tunisia        panama             2             1      0
111      belgium       england             1             0      0
112    argentina        france             3             4      1
113     portugal       uruguay             1             2      1
114       russia         spain             1             1      1
115      denmark       croatia             1             1      1
116       mexico        brazil             0             2      1
117        japan       belgium             2             3      1
118  switzerland        sweden             0             1      1
119      england      columbia             1             1      1
120       france       uruguay             2             0      2
121      belgium        brazil             2             1      2
122      england        sweden             2             0      2
123      croatia        russia             2             2      2
124      belgium        france             0             1      3
125      croatia       england             2             1      3
126      england       belgium             0             2      4
127      croatia        france             2             4      5

[128 rows x 5 columns]

In [233]:
df

,country,fifa_rank,gdp_rank,population_rank,avg_age,elo_ranking,star_count,coach_performance,home_country_adv,home_continent_adv,...,spi,global_o,global_d,avg_players_appearance,avg_players_goal,Happiness.Score,Health..Life.Expectancy.,Freedom,Generosity,Trust..Government.Corruption.
0,russia,70,60,9,28.1,1697,1,32,1,1,...,70.14205,1.94268,0.80439,28.521739,2.434783,5.963,0.547349,0.373783,0.052264,0.032963
1,saudi arabia,67,37,47,28.7,1574,0,9,0,0,...,51.33380,1.47177,1.20177,34.304348,3.956522,6.344,0.590148,0.449751,0.147616,0.273432
2,egypt,45,132,14,27.0,1659,1,15,0,0,...,62.46236,1.60808,0.85654,37.304348,2.782609,4.735,0.520187,0.282110,0.128631,0.114381
3,uruguay,14,45,133,28.7,1866,3,7,0,0,...,79.52363,2.28530,0.62285,42.260870,5.826087,6.454,0.719217,0.579392,0.175097,0.178062
4,portugal,4,36,84,27.7,1995,3,5,0,0,...,83.46619,2.40348,0.50431,39.521739,6.173913,5.195,0.795844,0.498465,0.095103,0.015869
5,spain,10,31,28,28.0,2031,6,4,0,1,...,91.30254,3.21114,0.46145,42.217391,4.565217,6.403,0.888961,0.408781,0.190134,0.070914
6,morocco,41,125,40,27.2,1691,0,8,0,0,...,72.33079,1.86875,0.65756,24.043478,2.608696,5.235,0.597711,0.408158,0.032210,0.087763
7,iran,37,92,17,26.5,1799,0,14,0,0,...,65.56769,1.60243,0.72717,30.521739,4.739130,4.692,0.639333,0.249323,0.387243,0.048761
8,france,7,24,21,26.4,1989,5,12,0,1,...,87.17682,2.88582,0.56975,26.043478,3.782609,6.442,0.844466,0.470222,0.129762,0.172502
9,australia,36,10,56,26.9,1727,0,23,0,0,...,61.68548,1.79230,1.04721,29.826087,5.260870,7.284,0.843887,0.601607,0.477699,0.301184
10,peru,11,84,43,27.0,1881,0,11,0,0,...,72.15616,1.97974,0.74528,34.086957,4.130435,5.715,0.630166,0.450003,0.126820,0.047049
11,denmark,12,9,116,26.1,1842,1,19,0,1,...,74.74844,2.13883,0.74455,26.565217,2.826087,7.522,0.792566,0.626007,0.355280,0.400770
12,argentina,5,53,31,28.4,1984,4,3,0,0,...,87.41192,2.58581,0.39899,37.347826,7.478261,6.599,0.695137,0.494519,0.109457,0.059740
13,iceland,22,4,178,29.0,1811,0,10,0,1,...,67.07394,1.92122,0.92018,40.043478,3.521739,7.504,0.833552,0.627163,0.475540,0.153527
14,croatia,20,56,128,27.5,1856,3,30,0,0,...,80.38099,2.28947,0.58512,40.304348,5.043478,5.293,0.701289,0.255772,0.248003,0.043103
15,nigeria,48,139,7,24.9,1696,0,20,0,0,...,70.08336,1.81501,0.71082,25.608696,2.434783,5.074,0.056916,0.394953,0.230947,0.026122
16,brazil,2,66,5,27.8,2114,4,2,0,0,...,92.81522,3.10876,0.30493,29.869565,5.521739,6.635,0.616552,0.437454,0.162350,0.111093
17,switzerland,6,2,98,26.6,1866,0,13,0,1,...,78.14181,2.28471,0.68735,37.347826,4.260870,7.494,0.858131,0.620071,0.290549,0.367007
18,costa rica,23,58,123,29.0,1746,1,28,0,0,...,64.89752,1.73368,0.86128,51.347826,5.000000,7.079,0.759509,0.580132,0.214613,0.100107
19,serbia,34,89,102,27.7,1769,0,31,0,1,...,73.82320,2.08408,0.74737,25.956522,2.826087,5.395,0.650785,0.208716,0.220126,0.040904
20,germany,1,17,19,25.7,2109,6,1,0,1,...,90.61094,3.23346,0.52224,41.086957,6.913043,6.951,0.798951,0.562511,0.336269,0.276732
21,mexico,15,70,11,27.4,1848,0,16,0,0,...,75.77906,2.16425,0.71564,60.304348,9.000000,6.578,0.709979,0.412730,0.120990,0.132774
22,sweden,24,11,91,27.4,1825,1,24,0,1,...,73.86757,2.05513,0.72496,31.304348,3.173913,7.284,0.830875,0.612924,0.385399,0.384399
23,south korea,57,28,27,26.5,1760,1,25,0,0,...,60.13670,1.61593,0.95934,29.304348,3.347826,5.838,0.900214,0.257922,0.206674,0.063283
24,belgium,3,18,77,27.0,1927,5,21,0,1,...,85.40682,2.81096,0.63262,47.260870,6.782609,6.891,0.818092,0.539771,0.231503,0.251343
25,panama,55,51,131,29.4,1671,0,17,0,0,...,56.47272,1.45612,0.96652,58.478261,6.304348,6.452,0.706156,0.550027,0.210557,0.070984
26,tunisia,21,118,79,26.8,1624,0,26,0,0,...,59.59496,1.62315,0.98848,20.173913,1.565217,4.805,0.613212,0.289681,0.049693,0.086723
27,england,21,22,22,25.9,1933,2,22,0,1,...,83.72824,2.34392,0.45752,20.956522,2.565217,6.714,0.805336,0.508190,0.492774,0.265428
28,poland,8,55,36,28.0,1842,2,18,0,1,...,73.28044,2.18065,0.84065,35.478261,5.478261,5.973,0.699475,0.520342,0.158466,0.059308
29,senegal,27,155,71,26.4,1752,1,29,0,0,...,65.96802,1.65995,0.75761,27.130435,3.173913,4.535,0.409363,0.377922,0.183469,0.115460
30,columbia,16,85,29,27.3,1927,3,6,0,0,...,80.52894,2.18240,0.51246,31.000000,3.956522,6.357,0.595028,0.477487,0.149014,0.046669
31,japan,61,25,10,27.5,1706,0,27,0,0,...,71.43255,2.06588,0.84009,45.000000,7.086957,5.920,0.913476,0.505626,0.120573,0.163761

In [234]:
group=group_result

In [235]:
group

          team_1        team_2  team_1_score  team_2_score  stage
0         russia  saudi arabia             5             0      0
1          egypt       uruguay             0             1      0
2        morocco          iran             0             1      0
3       portugal         spain             3             3      0
4         france     australia             2             1      0
5      argentina       iceland             1             1      0
6           peru       denmark             0             1      0
7        croatia       nigeria             2             0      0
8     costa rica        serbia             0             1      0
9        germany        mexico             0             1      0
10        brazil   switzerland             1             1      0
11        sweden   south korea             1             0      0
12       belgium        panama             3             0      0
13       tunisia       england             1             2      0
14      columbia         japan             1             2      0
15        poland       senegal             1             2      0
16        russia         egypt             3             1      0
17      portugal       morocco             1             0      0
18       uruguay  saudi arabia             1             0      0
19          iran         spain             0             1      0
20       denmark     australia             1             1      0
21        france          peru             1             0      0
22     argentina       croatia             0             3      0
23        brazil    costa rica             2             0      0
24       nigeria       iceland             2             0      0
25        serbia   switzerland             1             2      0
26       belgium       tunisia             5             2      0
27   south korea        mexico             1             2      0
28       germany        sweden             2             1      0
29       england        panama             6             1      0
..           ...           ...           ...           ...    ...
98      portugal          iran             1             1      0
99       morocco         spain             2             2      0
100       france       denmark             0             0      0
101         peru     australia             2             0      0
102    argentina       nigeria             2             1      0
103      croatia       iceland             2             1      0
104       sweden        mexico             3             0      0
105      germany   south korea             0             2      0
106       brazil        serbia             2             0      0
107   costa rica   switzerland             2             2      0
108       poland         japan             1             0      0
109     columbia       senegal             1             0      0
110      tunisia        panama             2             1      0
111      belgium       england             1             0      0
112    argentina        france             3             4      1
113     portugal       uruguay             1             2      1
114       russia         spain             1             1      1
115      denmark       croatia             1             1      1
116       mexico        brazil             0             2      1
117        japan       belgium             2             3      1
118  switzerland        sweden             0             1      1
119      england      columbia             1             1      1
120       france       uruguay             2             0      2
121      belgium        brazil             2             1      2
122      england        sweden             2             0      2
123      croatia        russia             2             2      2
124      belgium        france             0             1      3
125      croatia       england             2             1      3
126      england       belgium             0             2      4
127      croatia        france             2             4      5

[128 rows x 5 columns]

In [236]:
group['fifa_rank1'] = np.nan
group['avg_age1'] = np.nan
group['elo1'] = np.nan
group['star_count1'] = np.nan
group['coach_performance1'] = np.nan
group['home_country_adv1'] = np.nan
group['home_continent_adv1'] = np.nan
group['last_best_performance1'] = np.nan
group['final1'] = np.nan
group['semi1'] = np.nan
group['foreign_club1'] = np.nan
group['att1'] = np.nan
group['def1'] = np.nan
group['mid1'] = np.nan
group['ovr1'] = np.nan
group['power_index1'] = np.nan
group['offensive1'] = np.nan
group['defensive1'] = np.nan
group['avg_players_appearance1'] = np.nan
group['avg_players_goal1'] = np.nan
group['gdp1'] = np.nan
group['population1'] = np.nan
group['country_happiness_rank1'] = np.nan
group['happiness_score1'] = np.nan
group['life_expectancy1'] = np.nan
group['freedom1'] = np.nan
group['generosity1'] = np.nan
group['goverment_corruption1'] = np.nan




group['fifa_rank2'] = np.nan
group['avg_age2'] = np.nan
group['elo2'] = np.nan
group['star_count2'] = np.nan
group['coach_performance2'] = np.nan
group['home_country_adv2'] = np.nan
group['home_continent_adv2'] = np.nan
group['last_best_performance2'] = np.nan
group['final2'] = np.nan
group['semi2'] = np.nan
group['foreign_club2'] = np.nan
group['att2'] = np.nan
group['def2'] = np.nan
group['mid2'] = np.nan
group['ovr2'] = np.nan
group['power_index2'] = np.nan
group['offensive2'] = np.nan
group['defensive2'] = np.nan
group['avg_players_appearance2'] = np.nan
group['avg_players_goal2'] = np.nan
group['gdp2'] = np.nan
group['population2'] = np.nan
group['country_happiness_rank2'] = np.nan
group['happiness_score2'] = np.nan
group['life_expectancy2'] = np.nan
group['freedom2'] = np.nan
group['generosity2'] = np.nan
group['goverment_corruption2'] = np.nan
for index, row in group.iterrows():
    
    team1 = row.team_1
    team2 = row.team_2
    try:
        group.loc[index, 'fifa_rank1'] = df[df.country == team1]['fifa_rank'].iloc[0]
        group.loc[index, 'gdp1'] = df[df.country == team1]['gdp_rank'].iloc[0]
        group.loc[index, 'population1'] = df[df.country == team1]['population_rank'].iloc[0]
        group.loc[index, 'elo1'] = df[df.country == team1]['elo_ranking'].iloc[0]
        group.loc[index, 'avg_age1'] = df[df.country == team1]['avg_age'].iloc[0]
        group.loc[index, 'star_count1'] = df[df.country == team1]['star_count'].iloc[0]
        group.loc[index, 'coach_performance1'] = df[df.country == team1]['coach_performance'].iloc[0]
        group.loc[index, 'home_country_adv1'] = df[df.country == team1]['home_country_adv'].iloc[0]
        group.loc[index, 'home_continent_adv1'] = df[df.country == team1]['home_continent_adv'].iloc[0]
        group.loc[index, 'last_best_performance1'] = df[df.country == team1]['last_best_performance'].iloc[0]
        group.loc[index, 'final1'] = df[df.country == team1]['Previous_final'].iloc[0]
        group.loc[index, 'semi1'] = df[df.country == team1]['Previous_semi_final'].iloc[0]
        group.loc[index, 'foreign_club1'] = df[df.country == team1]['% of player in foreign club'].iloc[0]
        group.loc[index, 'att1'] = df[df.country == team1]['att'].iloc[0]
        group.loc[index, 'def1'] = df[df.country == team1]['def'].iloc[0]
        group.loc[index, 'mid1'] = df[df.country == team1]['mid'].iloc[0]
        group.loc[index, 'ovr1'] = df[df.country == team1]['ovr'].iloc[0]
        group.loc[index, 'happiness_score1'] = df[df.country == team1]['Happiness.Score'].iloc[0]
        group.loc[index, 'life_expectancy1'] = df[df.country == team1]['Health..Life.Expectancy.'].iloc[0]
        group.loc[index, 'freedom1'] = df[df.country == team1]['Freedom'].iloc[0]
        group.loc[index, 'generosity1'] = df[df.country == team1]['Generosity'].iloc[0]
        group.loc[index, 'goverment_corruption1'] = df[df.country == team1]['Trust..Government.Corruption.'].iloc[0]
        group.loc[index, 'power_index1'] = df[df.country == team1]['spi'].iloc[0]
        group.loc[index, 'offensive1'] = df[df.country == team1]['global_o'].iloc[0]
        group.loc[index, 'defensive1'] = df[df.country == team1]['global_d'].iloc[0]
        group.loc[index, 'avg_players_appearance1'] = df[df.country == team1]['avg_players_appearance'].iloc[0]
        group.loc[index, 'avg_players_goal1'] = df[df.country == team1]['avg_players_goal'].iloc[0]
        group.loc[index, 'country_happiness_rank1'] = integrate_features_happy[integrate_features_happy.country == team1]['Happiness.Rank'].iloc[0]
       
        group.loc[index, 'power_index2'] = df[df.country == team2]['spi'].iloc[0]
        group.loc[index, 'offensive2'] = df[df.country == team2]['global_o'].iloc[0]
        group.loc[index, 'defensive2'] = df[df.country == team2]['global_d'].iloc[0]
        group.loc[index, 'avg_players_appearance2'] = df[df.country == team2]['avg_players_appearance'].iloc[0]
        group.loc[index, 'avg_players_goal2'] = df[df.country == team2]['avg_players_goal'].iloc[0]
        group.loc[index, 'country_happiness_rank2'] = integrate_features_happy[integrate_features_happy.country == team2]['Happiness.Rank'].iloc[0]
        group.loc[index, 'happiness_score2'] = df[df.country == team2]['Happiness.Score'].iloc[0]
        group.loc[index, 'life_expectancy2'] = df[df.country == team2]['Health..Life.Expectancy.'].iloc[0]
        group.loc[index, 'freedom2'] = df[df.country == team2]['Freedom'].iloc[0]
        group.loc[index, 'generosity2'] = df[df.country == team2]['Generosity'].iloc[0]
        group.loc[index, 'goverment_corruption2'] = df[df.country == team2]['Trust..Government.Corruption.'].iloc[0]
        group.loc[index, 'fifa_rank2'] = df[df.country == team2]['fifa_rank'].iloc[0]
        group.loc[index, 'gdp2'] = df[df.country == team2]['gdp_rank'].iloc[0]
        group.loc[index, 'population2'] = df[df.country == team2]['population_rank'].iloc[0]
        group.loc[index, 'elo2'] = df[df.country == team2]['elo_ranking'].iloc[0]
        group.loc[index, 'avg_age2'] = df[df.country == team2]['avg_age'].iloc[0]
        group.loc[index, 'star_count2'] = df[df.country == team2]['star_count'].iloc[0]
        group.loc[index, 'coach_performance2'] = df[df.country == team2]['coach_performance'].iloc[0]
        group.loc[index, 'home_country_adv2'] = df[df.country == team2]['home_country_adv'].iloc[0]
        group.loc[index, 'home_continent_adv2'] = df[df.country == team2]['home_continent_adv'].iloc[0]
        group.loc[index, 'last_best_performance2'] = df[df.country == team2]['last_best_performance'].iloc[0]
        group.loc[index, 'final2'] = df[df.country == team2]['Previous_final'].iloc[0]
        group.loc[index, 'semi2'] = df[df.country == team2]['Previous_semi_final'].iloc[0]
        group.loc[index, 'foreign_club2'] = df[df.country == team2]['% of player in foreign club'].iloc[0]
        group.loc[index, 'att2'] = df[df.country == team2]['att'].iloc[0]
        group.loc[index, 'def2'] = df[df.country == team2]['def'].iloc[0]
        group.loc[index, 'mid2'] = df[df.country == team2]['mid'].iloc[0]
        group.loc[index, 'ovr2'] = df[df.country == team2]['ovr'].iloc[0]
        
    except:
        pass
group['fifa_rank'] = group['fifa_rank1'] - group['fifa_rank2']
group['elo'] = group['elo1'] - group['elo2']
group['avg_age'] = group['avg_age1'] - group['avg_age2']
group['home_country_adv'] = group['home_country_adv1'] - group['home_country_adv2']
group['home_continent_adv'] = group['home_continent_adv1'] - group['home_continent_adv2']
group['last_best_performance'] = group['last_best_performance1'] - group['last_best_performance2']
group['star_count'] = group['star_count1'] - group['star_count2']
group['coach_performance'] = group['coach_performance1'] - group['coach_performance2']
group['final'] = group['final1'] - group['final2']
group['semi'] = group['semi1'] - group['semi2']
group['foreign_club'] = group['foreign_club1'] - group['foreign_club2']
group['att'] = group['att1'] - group['att2']
group['def'] = group['def1'] - group['def2']
group['mid'] = group['mid1'] - group['mid2']
group['ovr'] = group['ovr1'] - group['ovr2']
group['power_index'] = group['power_index1']-group['power_index2']
group['offensive'] = group['offensive1']-group['offensive2']
group['defensive'] = group['defensive1']-group['defensive2']
group['avg_players_appearance'] = group['avg_players_appearance1']-group['avg_players_appearance2']
group['avg_players_goal'] = group['avg_players_goal1']-group['avg_players_goal2']
group['country_happiness_rank'] = group['country_happiness_rank1']-group['country_happiness_rank2']
group['gdp'] = group['gdp1'] - group['gdp2']
group['population'] = group['population1'] - group['population2']
group['happiness_score'] = group['happiness_score1']-group['happiness_score2']
group['life_expectancy'] = group['life_expectancy1']-group['life_expectancy2']
group['freedom'] = group['freedom1']-group['freedom2']
group['generosity'] = group['generosity1']-group['generosity2']
group['goverment_corruption'] = group['goverment_corruption1']-group['goverment_corruption2']

In [237]:
group.to_csv('loo_test_train_data_v29_16_16_with_stage.csv')

In [238]:
group['score'] = group.team_1_score - group.team_2_score
group['winner'] = None
group['winner'][group.score > 0] = 1 #Team-1 win
group['winner'][group.score < 0] = -1 #Team-2 win
group['winner'][group.score == 0] = 0 # Draw

In [239]:
group=group.drop('team_1_score', 1)
group=group.drop('team_2_score', 1)
group=group.drop('score', 1)

In [240]:
group.to_csv('loo_train_test.csv')

In [241]:
group=pd.read_csv('loo_train_test.csv')

In [242]:
group

,Unnamed: 0,team_1,team_2,stage,fifa_rank1,avg_age1,elo1,star_count1,coach_performance1,home_country_adv1,...,avg_players_goal,country_happiness_rank,gdp,population,happiness_score,life_expectancy,freedom,generosity,goverment_corruption,winner
0,0,russia,saudi arabia,0,70.0,28.1,1697.0,1.0,32.0,1.0,...,-1.521739,12.0,23.0,-38.0,-0.381,-0.042799,-0.075967,-0.095352,-0.240469,1
1,1,egypt,uruguay,0,45.0,27.0,1659.0,1.0,15.0,0.0,...,-3.043478,76.0,87.0,-119.0,-1.719,-0.199030,-0.297282,-0.046465,-0.063681,-1
2,2,morocco,iran,0,41.0,27.2,1691.0,0.0,8.0,0.0,...,-2.130435,-24.0,33.0,23.0,0.543,-0.041623,0.158836,-0.355033,0.039002,-1
3,3,portugal,spain,0,4.0,27.7,1995.0,3.0,5.0,0.0,...,1.608696,55.0,5.0,56.0,-1.208,-0.093117,0.089684,-0.095031,-0.055045,0
4,4,france,australia,0,7.0,26.4,1989.0,5.0,12.0,0.0,...,-1.478261,21.0,14.0,-35.0,-0.842,0.000579,-0.131385,-0.347937,-0.128681,1
5,5,argentina,iceland,0,5.0,28.4,1984.0,4.0,3.0,0.0,...,3.956522,21.0,49.0,-147.0,-0.905,-0.138415,-0.132643,-0.366083,-0.093787,0
6,6,peru,denmark,0,11.0,27.0,1881.0,0.0,11.0,0.0,...,1.304348,61.0,75.0,-73.0,-1.807,-0.162399,-0.176004,-0.228461,-0.353721,-1
7,7,croatia,nigeria,0,20.0,27.5,1856.0,3.0,30.0,0.0,...,2.608696,-18.0,-83.0,121.0,0.219,0.644373,-0.139180,0.017056,0.016982,1
8,8,costa rica,serbia,0,23.0,29.0,1746.0,1.0,28.0,0.0,...,2.173913,-61.0,-31.0,21.0,1.684,0.108725,0.371416,-0.005513,0.059203,-1
9,9,germany,mexico,0,1.0,25.7,2109.0,6.0,1.0,0.0,...,-2.086957,-9.0,-53.0,8.0,0.373,0.088972,0.149781,0.215279,0.143958,-1
10,10,brazil,switzerland,0,2.0,27.8,2114.0,4.0,2.0,0.0,...,1.260870,18.0,64.0,-93.0,-0.859,-0.241579,-0.182617,-0.128199,-0.255915,0
11,11,sweden,south korea,0,24.0,27.4,1825.0,1.0,24.0,0.0,...,-0.173913,-46.0,-17.0,64.0,1.446,-0.069339,0.355002,0.178725,0.321116,1
12,12,belgium,panama,0,3.0,27.0,1927.0,5.0,21.0,0.0,...,0.478261,-13.0,-33.0,-54.0,0.439,0.111936,-0.010256,0.020946,0.180359,1
13,13,tunisia,england,0,21.0,26.8,1624.0,0.0,26.0,0.0,...,-1.000000,83.0,96.0,57.0,-1.909,-0.192124,-0.218509,-0.443081,-0.178705,-1
14,14,columbia,japan,0,16.0,27.3,1927.0,3.0,6.0,0.0,...,-3.130435,-15.0,60.0,19.0,0.437,-0.318448,-0.028138,0.028442,-0.117092,-1
15,15,poland,senegal,0,8.0,28.0,1842.0,2.0,18.0,0.0,...,2.304348,-69.0,-100.0,-35.0,1.438,0.290112,0.142420,-0.025003,-0.056153,-1
16,16,russia,egypt,0,70.0,28.1,1697.0,1.0,32.0,1.0,...,-0.347826,-55.0,-72.0,-5.0,1.228,0.027162,0.091673,-0.076368,-0.081418,1
17,17,portugal,morocco,0,4.0,27.7,1995.0,3.0,5.0,0.0,...,3.565217,5.0,-89.0,44.0,-0.040,0.198133,0.090307,0.062893,-0.071894,1
18,18,uruguay,saudi arabia,0,14.0,28.7,1866.0,3.0,7.0,0.0,...,1.869565,-9.0,8.0,86.0,0.110,0.129068,0.129642,0.027481,-0.095370,1
19,19,iran,spain,0,37.0,26.5,1799.0,0.0,14.0,0.0,...,0.173913,74.0,61.0,-11.0,-1.711,-0.249627,-0.159459,0.197109,-0.022153,-1
20,20,denmark,australia,0,12.0,26.1,1842.0,1.0,19.0,0.0,...,-2.434783,-8.0,-1.0,60.0,0.238,-0.051321,0.024399,-0.122419,0.099586,0
21,21,france,peru,0,7.0,26.4,1989.0,5.0,12.0,0.0,...,-0.347826,-32.0,-60.0,-22.0,0.727,0.214300,0.020219,0.002943,0.125453,1
22,22,argentina,croatia,0,5.0,28.4,1984.0,4.0,3.0,0.0,...,2.434783,-53.0,-3.0,-97.0,1.306,-0.006151,0.238747,-0.138546,0.016637,-1
23,23,brazil,costa rica,0,2.0,27.8,2114.0,4.0,2.0,0.0,...,0.521739,10.0,8.0,-118.0,-0.444,-0.142957,-0.142678,-0.052263,0.010986,1
24,24,nigeria,iceland,0,48.0,24.9,1696.0,0.0,20.0,0.0,...,-1.086957,92.0,135.0,-171.0,-2.430,-0.776636,-0.232210,-0.244593,-0.127405,1
25,25,serbia,switzerland,0,34.0,27.7,1769.0,0.0,31.0,0.0,...,-1.434783,69.0,87.0,4.0,-2.099,-0.207347,-0.411355,-0.070423,-0.326104,-1
26,26,belgium,tunisia,0,3.0,27.0,1927.0,5.0,21.0,0.0,...,5.217391,-85.0,-100.0,-2.0,2.086,0.204880,0.250090,0.181810,0.164620,1
27,27,south korea,mexico,0,57.0,26.5,1760.0,1.0,25.0,0.0,...,-5.652174,30.0,-42.0,16.0,-0.740,0.190235,-0.154808,0.085684,-0.069491,-1
28,28,germany,sweden,0,1.0,25.7,2109.0,6.0,1.0,0.0,...,3.739130,7.0,6.0,-72.0,-0.333,-0.031924,-0.050413,-0.049130,-0.107667,1
29,29,england,panama,0,21.0,25.9,1933.0,2.0,22.0,0.0,...,-3.739130,-11.0,-29.0,-109.0,0.262,0.099180,-0.041837,0.282217,0.194444,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
98,98,portugal,iran,0,4.0,27.7,1995.0,3.0,5.0,0.0,...,1.434783,-19.0,-56.0,67.0,0.503,0.156510,0.249143,-0.292140,-0.032892,0
99,99,morocco,spain,0,41.0,27.2,1691.0,0.0,8.0,0.0,...,-1.956522,50.0,94.0,12.0,-1.168,-0.291250,-0.000623,-0.157924,0.016849,0
100,100,france,denmark,0,7.0,26.4,1989.0,5.0,12.0,0.0,...,0.956522,29.0,15.0,-95.0,-1.080,0.051900,-0.155785,-0.225518,-0.228268,0
101,101,peru,australia,0,11.0,27.0,1881.0,0.0,11.0,0.0,...,-1.130435,53.0,74.0,-13.0,-1.569,-0.213721,-0.151605,-0.350880,-0.254135,1
102,102,argentina,nigeria,0,5.0,28.4,1984.0,4.0,3.0,0.0,...,5.043478,-71.0,-86.0,24.0,1.525,0.638221,0.099567,-0.121490,0.033618,1
103,103,croatia,iceland,0,20.0,27.5,1856.0,3.0,30.0,0.0,...,1.521739,74.0,52.0,-50.0,-2.211,-0.132264,-0.371390,-0.227537,-0.110423,1
104,104,sweden,mexico,0,24.0,27.4,1825.0,1.0,24.0,0.0,...,-5.826087,-16.0,-59.0,80.0,0.706,0.120896,0.200194,0.264409,0.251625,1
105,105,germany,south korea,0,1.0,25.7,2109.0,6.0,1.0,0.0,...,3.565217,-39.0,-11.0,-8.0,1.113,-0.101263,0.304590,0.129595,0.213449,-1
106,106,brazil,serbia,0,2.0,27.8,2114.0,4.0,2.0,0.0,...,2.695652,-51.0,-23.0,-97.0,1.240,-0.034232,0.228738,-0.057776,0.070189,1
107,107,costa rica,switzerland,0,23.0,29.0,1746.0,1.0,28.0,0.0,...,0.739130,8.0,56.0,25.0,-0.415,-0.098622,-0.039939,-0.075936,-0.266901,0
108,108,poland,japan,0,8.0,28.0,1842.0,2.0,18.0,0.0,...,-1.608696,-5.0,30.0,26.0,0.053,-0.214001,0.014717,0.037893,-0.104453,1
109,109,columbia,senegal,0,16.0,27.3,1927.0,3.0,6.0,0.0,...,0.782609,-79.0,-70.0,-42.0,1.822,0.185665,0.099565,-0.034454,-0.068792,1
110,110,tunisia,panama,0,21.0,26.8,1624.0,0.0,26.0,0.0,...,-4.739130,72.0,67.0,-52.0,-1.647,-0.092944,-0.260346,-0.160864,0.015739,1
111,111,belgium,england,0,3.0,27.0,1927.0,5.0,21.0,0.0,...,4.217391,-2.0,-4.0,55.0,0.177,0.012756,0.031581,-0.261271,-0.014085,1
112,112,argentina,france,1,5.0,28.4,1984.0,4.0,3.0,0.0,...,3.695652,-7.0,29.0,10.0,0.157,-0.149329,0.024297,-0.020305,-0.112763,-1
113,113,portugal,uruguay,1,4.0,27.7,1995.0,3.0,5.0,0.0,...,0.347826,61.0,-9.0,-49.0,-1.259,0.076627,-0.080927,-0.079994,-0.162192,-1
114,114,russia,spain,1,70.0,28.1,1697.0,1.0,32.0,1.0,...,-2.130435,15.0,29.0,-19.0,-0.440,-0.341611,-0.034998,-0.137870,-0.037951,0
115,115,denmark,croatia,1,12.0,26.1,1842.0,1.0,19.0,0.0,...,-2.217391,-75.0,-47.0,-12.0,2.229,0.091277,0.370234,0.107278,0.357667,0
116,116,mexico,brazil,1,15.0,27.4,1848.0,0.0,16.0,0.0,...,3.478261,3.0,4.0,6.0,-0.057,0.093427,-0.024724,-0.041359,0.021681,-1
117,117,japan,belgium,1,61.0,27.5,1706.0,0.0,27.0,0.0,...,0.304348,34.0,7.0,-67.0,-0.971,0.095384,-0.034145,-0.110931,-0.087582,-1
118,118,switzerland,sweden,1,6.0,26.6,1866.0,0.0,13.0,0.0,...,1.086957,-5.0,-9.0,7.0,0.210,0.027256,0.007146,-0.094850,-0.017391,-1
119,119,england,columbia,1,21.0,25.9,1933.0,2.0,22.0,0.0,...,-1.391304,-17.0,-63.0,-7.0,0.357,0.210308,0.030703,0.343760,0.218759,0
120,120,france,uruguay,2,7.0,26.4,1989.0,5.0,12.0,0.0,...,-2.043478,3.0,-21.0,-112.0,-0.012,0.125249,-0.109170,-0.045335,-0.005559,1
121,121,belgium,brazil,2,3.0,27.0,1927.0,5.0,21.0,0.0,...,1.260870,-5.0,-48.0,72.0,0.256,0.201540,0.102317,0.069153,0.140250,1
122,122,england,sweden,2,21.0,25.9,1933.0,2.0,22.0,0.0,...,-0.608696,10.0,11.0,-69.0,-0.570,-0.025539,-0.104734,0.107375,-0.118971,1
123,123,croatia,russia,2,20.0,27.5,1856.0,3.0,30.0,0.0,...,2.608696,28.0,-4.0,119.0,-0.670,0.153939,-0.118011,0.195739,0.010140,0
124,124,belgium,france,3,3.0,27.0,1927.0,5.0,21.0,0.0,...,3.000000,-14.0,-6.0,56.0,0.449,-0.026374,0.069549,0.101741,0.078841,-1
125,125,croatia,england,3,20.0,27.5,1856.0,3.0,30.0,0.0,...,2.478261,58.0,34.0,106.0,-1.421,-0.104047,-0.252418,-0.244771,-0.222325,1
126,126,england,belgium,4,21.0,25.9,1933.0,2.0,22.0,0.0,...,-4.217391,2.0,4.0,-55.0,-0.177,-0.012756,-0.031581,0.261271,0.014085,-1
127,127,croatia,france,5,20.0,27.5,1856.0,3.0,30.0,0.0,...,1.260870,46.0,32.0,107.0,-1.149,-0.143177,-0.214450,0.118241,-0.129399,-1

In [61]:
group_train_data = group.head(48)

In [63]:
group_train_data=group_train_data.drop('Unnamed: 0', 1)

In [66]:
#group_train_data
group_train_data.to_csv('train_data.csv')

In [68]:
group_test_data = group.tail(16)

In [70]:
group_test_data=group_test_data.drop('Unnamed: 0', 1)

In [72]:
group_test_data.to_csv('test_data.csv')

In [73]:
#group_test_data

,team_1,team_2,fifa_rank1,avg_age1,elo1,star_count1,coach_performance1,home_country_adv1,home_continent_adv1,last_best_performance1,...,avg_players_appearance,country_happiness_rank,gdp,population,happiness_score,life_expectancy,freedom,generosity,goverment_corruption,winner
48,france,argentina,7.0,26.4,1989.0,5.0,12.0,0.0,1.0,7.0,...,-11.304348,7.0,-29.0,-10.0,-0.157,0.149329,-0.024297,0.020305,0.112763,1
49,uruguay,portugal,14.0,28.7,1866.0,3.0,7.0,0.0,0.0,10.0,...,2.739130,-61.0,9.0,49.0,1.259,-0.076627,0.080927,0.079994,0.162192,1
50,spain,russia,10.0,28.0,2031.0,6.0,4.0,0.0,1.0,6.0,...,13.695652,-15.0,-29.0,19.0,0.440,0.341611,0.034998,0.137870,0.037951,0
51,croatia,denmark,20.0,27.5,1856.0,3.0,30.0,0.0,0.0,34.0,...,13.739130,75.0,47.0,12.0,-2.229,-0.091277,-0.370234,-0.107278,-0.357667,0
52,brazil,mexico,2.0,27.8,2114.0,4.0,2.0,0.0,0.0,1.0,...,-30.434783,-3.0,-4.0,-6.0,0.057,-0.093427,0.024724,0.041359,-0.021681,1
53,belgium,japan,3.0,27.0,1927.0,5.0,21.0,0.0,1.0,9.0,...,2.260870,-34.0,-7.0,67.0,0.971,-0.095384,0.034145,0.110931,0.087582,1
54,sweden,switzerland,24.0,27.4,1825.0,1.0,24.0,0.0,1.0,12.0,...,-6.043478,5.0,9.0,-7.0,-0.210,-0.027256,-0.007146,0.094850,0.017391,1
55,columbia,england,16.0,27.3,1927.0,3.0,6.0,0.0,0.0,31.0,...,10.043478,17.0,63.0,7.0,-0.357,-0.210308,-0.030703,-0.343760,-0.218759,0
56,uruguay,france,14.0,28.7,1866.0,3.0,7.0,0.0,0.0,10.0,...,16.217391,-3.0,21.0,112.0,0.012,-0.125249,0.109170,0.045335,0.005559,-1
57,brazil,belgium,2.0,27.8,2114.0,4.0,2.0,0.0,0.0,1.0,...,-17.391304,5.0,48.0,-72.0,-0.256,-0.201540,-0.102317,-0.069153,-0.140250,-1
58,sweden,england,24.0,27.4,1825.0,1.0,24.0,0.0,1.0,12.0,...,10.347826,-10.0,-11.0,69.0,0.570,0.025539,0.104734,-0.107375,0.118971,-1
59,russia,croatia,70.0,28.1,1697.0,1.0,32.0,1.0,1.0,14.0,...,-11.782609,-28.0,4.0,-119.0,0.670,-0.153939,0.118011,-0.195739,-0.010140,0
60,france,belgium,7.0,26.4,1989.0,5.0,12.0,0.0,1.0,7.0,...,-21.217391,14.0,6.0,-56.0,-0.449,0.026374,-0.069549,-0.101741,-0.078841,1
61,england,croatia,21.0,25.9,1933.0,2.0,22.0,0.0,1.0,8.0,...,-19.347826,-58.0,-34.0,-106.0,1.421,0.104047,0.252418,0.244771,0.222325,-1
62,belgium,england,3.0,27.0,1927.0,5.0,21.0,0.0,1.0,9.0,...,26.304348,-2.0,-4.0,55.0,0.177,0.012756,0.031581,-0.261271,-0.014085,1
63,france,croatia,7.0,26.4,1989.0,5.0,12.0,0.0,1.0,7.0,...,-14.260870,-46.0,-32.0,-107.0,1.149,0.143177,0.214450,-0.118241,0.129399,1

In [120]:
train_data_match_stage

          team_1        team_2  team_1_score  team_2_score  stage
0         russia  saudi arabia             5             0      0
1          egypt       uruguay             0             1      0
2        morocco          iran             0             1      0
3       portugal         spain             3             3      0
4         france     australia             2             1      0
5      argentina       iceland             1             1      0
6           peru       denmark             0             1      0
7        croatia       nigeria             2             0      0
8     costa rica        serbia             0             1      0
9        germany        mexico             0             1      0
10        brazil   switzerland             1             1      0
11        sweden   south korea             1             0      0
12       belgium        panama             3             0      0
13       tunisia       england             1             2      0
14      columbia         japan             1             2      0
15        poland       senegal             1             2      0
16        russia         egypt             3             1      0
17      portugal       morocco             1             0      0
18       uruguay  saudi arabia             1             0      0
19          iran         spain             0             1      0
20       denmark     australia             1             1      0
21        france          peru             1             0      0
22     argentina       croatia             0             3      0
23        brazil    costa rica             2             0      0
24       nigeria       iceland             2             0      0
25        serbia   switzerland             1             2      0
26       belgium       tunisia             5             2      0
27   south korea        mexico             1             2      0
28       germany        sweden             2             1      0
29       england        panama             6             1      0
30         japan       senegal             2             2      0
31        poland      columbia             0             3      0
32       uruguay        russia             3             0      0
33  saudi arabia         egypt             2             1      0
34          iran      portugal             1             1      0
35         spain       morocco             2             2      0
36       denmark        france             0             0      0
37     australia          peru             0             2      0
38       nigeria     argentina             1             2      0
39       iceland       croatia             1             2      0
40        mexico        sweden             0             3      0
41   south korea       germany             2             0      0
42        serbia        brazil             0             2      0
43   switzerland    costa rica             2             2      0
44         japan        poland             0             1      0
45       senegal      columbia             0             1      0
46        panama       tunisia             1             2      0
47       england       belgium             0             1      0

In [171]:
base_result=train_data_match_stage

In [172]:
#base_result=base_result.drop('Unnamed: 0', 1)
#base_result=team_wise_result

In [173]:
test_result=base_result

In [174]:
cols = list(test_result)
#cols = list(group)

cols[1], cols[0] = cols[0], cols[1]

cols[3], cols[2] = cols[2], cols[3]

test_result=test_result.ix[:,cols]

In [175]:
test_result

          team_2        team_1  team_2_score  team_1_score  stage
0   saudi arabia        russia             0             5      0
1        uruguay         egypt             1             0      0
2           iran       morocco             1             0      0
3          spain      portugal             3             3      0
4      australia        france             1             2      0
5        iceland     argentina             1             1      0
6        denmark          peru             1             0      0
7        nigeria       croatia             0             2      0
8         serbia    costa rica             1             0      0
9         mexico       germany             1             0      0
10   switzerland        brazil             1             1      0
11   south korea        sweden             0             1      0
12        panama       belgium             0             3      0
13       england       tunisia             2             1      0
14         japan      columbia             2             1      0
15       senegal        poland             2             1      0
16         egypt        russia             1             3      0
17       morocco      portugal             0             1      0
18  saudi arabia       uruguay             0             1      0
19         spain          iran             1             0      0
20     australia       denmark             1             1      0
21          peru        france             0             1      0
22       croatia     argentina             3             0      0
23    costa rica        brazil             0             2      0
24       iceland       nigeria             0             2      0
25   switzerland        serbia             2             1      0
26       tunisia       belgium             2             5      0
27        mexico   south korea             2             1      0
28        sweden       germany             1             2      0
29        panama       england             1             6      0
30       senegal         japan             2             2      0
31      columbia        poland             3             0      0
32        russia       uruguay             0             3      0
33         egypt  saudi arabia             1             2      0
34      portugal          iran             1             1      0
35       morocco         spain             2             2      0
36        france       denmark             0             0      0
37          peru     australia             2             0      0
38     argentina       nigeria             2             1      0
39       croatia       iceland             2             1      0
40        sweden        mexico             3             0      0
41       germany   south korea             0             2      0
42        brazil        serbia             2             0      0
43    costa rica   switzerland             2             2      0
44        poland         japan             1             0      0
45      columbia       senegal             1             0      0
46       tunisia        panama             2             1      0
47       belgium       england             1             0      0

In [176]:

test_result = test_result.rename(columns={'team_1': 'team_11'})

test_result = test_result.rename(columns={'team_2': 'team_22'})

test_result = test_result.rename(columns={'team_1_score': 'team_11_score'})

test_result = test_result.rename(columns={'team_2_score': 'team_22_score'})


#all_match_result=all_match_result.append(all_result)

In [177]:
test_result

         team_22       team_11  team_22_score  team_11_score  stage
0   saudi arabia        russia              0              5      0
1        uruguay         egypt              1              0      0
2           iran       morocco              1              0      0
3          spain      portugal              3              3      0
4      australia        france              1              2      0
5        iceland     argentina              1              1      0
6        denmark          peru              1              0      0
7        nigeria       croatia              0              2      0
8         serbia    costa rica              1              0      0
9         mexico       germany              1              0      0
10   switzerland        brazil              1              1      0
11   south korea        sweden              0              1      0
12        panama       belgium              0              3      0
13       england       tunisia              2              1      0
14         japan      columbia              2              1      0
15       senegal        poland              2              1      0
16         egypt        russia              1              3      0
17       morocco      portugal              0              1      0
18  saudi arabia       uruguay              0              1      0
19         spain          iran              1              0      0
20     australia       denmark              1              1      0
21          peru        france              0              1      0
22       croatia     argentina              3              0      0
23    costa rica        brazil              0              2      0
24       iceland       nigeria              0              2      0
25   switzerland        serbia              2              1      0
26       tunisia       belgium              2              5      0
27        mexico   south korea              2              1      0
28        sweden       germany              1              2      0
29        panama       england              1              6      0
30       senegal         japan              2              2      0
31      columbia        poland              3              0      0
32        russia       uruguay              0              3      0
33         egypt  saudi arabia              1              2      0
34      portugal          iran              1              1      0
35       morocco         spain              2              2      0
36        france       denmark              0              0      0
37          peru     australia              2              0      0
38     argentina       nigeria              2              1      0
39       croatia       iceland              2              1      0
40        sweden        mexico              3              0      0
41       germany   south korea              0              2      0
42        brazil        serbia              2              0      0
43    costa rica   switzerland              2              2      0
44        poland         japan              1              0      0
45      columbia       senegal              1              0      0
46       tunisia        panama              2              1      0
47       belgium       england              1              0      0

In [178]:
test_result = test_result.rename(columns={'team_11': 'team_2'})

test_result = test_result.rename(columns={'team_22': 'team_1'})

test_result = test_result.rename(columns={'team_11_score': 'team_2_score'})

test_result = test_result.rename(columns={'team_22_score': 'team_1_score'})

In [179]:
#all_match_result=all_match_result[['team_1','team_2','team_1_score','team_2_score']]

In [180]:
base_result=base_result.append(test_result)

In [181]:
base_result.to_csv('train_match_result_duplicate_with_stage_29J_15_58.csv')

In [182]:
base_result

          team_1        team_2  team_1_score  team_2_score  stage
0         russia  saudi arabia             5             0      0
1          egypt       uruguay             0             1      0
2        morocco          iran             0             1      0
3       portugal         spain             3             3      0
4         france     australia             2             1      0
5      argentina       iceland             1             1      0
6           peru       denmark             0             1      0
7        croatia       nigeria             2             0      0
8     costa rica        serbia             0             1      0
9        germany        mexico             0             1      0
10        brazil   switzerland             1             1      0
11        sweden   south korea             1             0      0
12       belgium        panama             3             0      0
13       tunisia       england             1             2      0
14      columbia         japan             1             2      0
15        poland       senegal             1             2      0
16        russia         egypt             3             1      0
17      portugal       morocco             1             0      0
18       uruguay  saudi arabia             1             0      0
19          iran         spain             0             1      0
20       denmark     australia             1             1      0
21        france          peru             1             0      0
22     argentina       croatia             0             3      0
23        brazil    costa rica             2             0      0
24       nigeria       iceland             2             0      0
25        serbia   switzerland             1             2      0
26       belgium       tunisia             5             2      0
27   south korea        mexico             1             2      0
28       germany        sweden             2             1      0
29       england        panama             6             1      0
..           ...           ...           ...           ...    ...
18  saudi arabia       uruguay             0             1      0
19         spain          iran             1             0      0
20     australia       denmark             1             1      0
21          peru        france             0             1      0
22       croatia     argentina             3             0      0
23    costa rica        brazil             0             2      0
24       iceland       nigeria             0             2      0
25   switzerland        serbia             2             1      0
26       tunisia       belgium             2             5      0
27        mexico   south korea             2             1      0
28        sweden       germany             1             2      0
29        panama       england             1             6      0
30       senegal         japan             2             2      0
31      columbia        poland             3             0      0
32        russia       uruguay             0             3      0
33         egypt  saudi arabia             1             2      0
34      portugal          iran             1             1      0
35       morocco         spain             2             2      0
36        france       denmark             0             0      0
37          peru     australia             2             0      0
38     argentina       nigeria             2             1      0
39       croatia       iceland             2             1      0
40        sweden        mexico             3             0      0
41       germany   south korea             0             2      0
42        brazil        serbia             2             0      0
43    costa rica   switzerland             2             2      0
44        poland         japan             1             0      0
45      columbia       senegal             1             0      0
46       tunisia        panama             2             1      0
47       belgium       england             1             0      0

[96 rows x 5 columns]